const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const src=fs.readFileSync(path.join(__dirname,'../cad/cad.js'),'utf8');
function setup(api){const elements={projectname:{value:'Job'},projectstatus:{textContent:''}},saved=[];const c={Blob,window:{navigator:{onLine:true}},projectRetryTimer:null,projectRetryAttempt:0,retries:[],retryProjectSave(...args){c.retries.push(args);},projectSaveStatus(state,text){elements.projectstatus.state=state;elements.projectstatus.textContent=text;},projectTimer:null,projectId:'12345678-1234-1234-1234-123456789abc',projectName:'Job',projectRevision:1,projectDirty:true,projectSaveChain:Promise.resolve(),panels:[{}],panelIndex:0,cloudRevisions:new Map(),clearTimeout(){},projectOwner:()=> 'account',rememberPanel(){},$:id=>elements[id],crypto:{randomUUID:()=> 'new-copy-123456789'},notice(){},api,PanelCadProjects:{snapshot:()=>({name:'Job',updatedAt:1,panels:[{}]}),save:async(...args)=>saved.push(args),saveCloud:async(data,id,revision,request)=>request('/cad/projects/'+id,{revision})}};vm.runInNewContext(src.slice(src.indexOf('async function saveProject()'),src.indexOf('function pickProject(')),c);return {c,elements,saved};}
test('failed account save preserves local copy and does not claim success',async()=>{const {c,elements,saved}=setup(async()=>{throw Error('Offline');});await assert.rejects(c.saveProject(),/Offline/);assert.equal(saved.length,1);assert.equal(c.projectDirty,true);assert.match(elements.projectstatus.textContent,/Account save failed/);});
test('successful save records server revision and account status',async()=>{const {c,elements}=setup(async()=>({revision:2}));await c.saveProject();assert.equal(c.projectDirty,false);assert.match(elements.projectstatus.textContent,/Saved to your account/);assert.equal([...c.cloudRevisions.values()][0],2);});
test('device conflict saves a separate account copy',async()=>{let calls=0;const {c,elements,saved}=setup(async()=>{if(!calls++){const e=Error('Conflict');e.conflict=true;throw e;}return {revision:1};});await c.saveProject();assert.equal(c.projectId,'new-copy-123456789');assert.equal(saved.length,2);assert.equal(c.projectDirty,false);assert.match(elements.projectstatus.textContent,/separate device copy/);});
test('offline saves stay local and wait for reconnect',async()=>{let calls=0;const {c,elements,saved}=setup(async()=>{calls++;return {revision:1};});c.window.navigator.onLine=false;await assert.rejects(c.saveProject(),/offline/);assert.equal(saved.length,1);assert.equal(calls,0);assert.equal(c.retries.length,0);assert.equal(elements.projectstatus.state,'offline');assert.match(elements.projectstatus.textContent,/saved on this device/);});
test('temporary errors schedule retries; validation errors do not',async()=>{const {c,elements}=setup(async()=>{const e=Error('Unavailable');e.status=503;throw e;});await assert.rejects(c.saveProject());assert.equal(c.retries[0][2],2000);assert.equal(elements.projectstatus.state,'retrying');const other=setup(async()=>{const e=Error('Too large');e.status=400;throw e;});await assert.rejects(other.c.saveProject());assert.equal(other.c.retries.length,0);assert.equal(other.elements.projectstatus.state,'error');});
test('failed local storage never reports a retained copy',async()=>{const {c,elements}=setup(async()=>({revision:1}));c.PanelCadProjects.save=async()=>{throw Error('Storage full');};await assert.rejects(c.saveProject());assert.equal(c.retries.length,0);assert.match(elements.projectstatus.textContent,/download a backup/);assert.doesNotMatch(elements.projectstatus.textContent,/Saved on this device/);});
