const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const c={window:{},structuredClone};for(const f of ['sketch-components.js','outline-correction.js']){vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../cad',f),'utf8'),c);c.PanelSketchComponents=c.window.PanelSketchComponents;}
const split=c.window.PanelOutlineCorrection.insertFoldPoint;
function fixture(){return {points:[{x:0,y:100},{x:100,y:100},{x:100,y:0},{x:0,y:0}],values:[{site:800,kind:'horizontal',code:'B'},{site:600,kind:'vertical',code:'S'},{site:800,kind:'horizontal',code:'B'},{site:600,kind:'vertical',code:'S'}],markedFolds:[{from:0,to:2}],rightAngles:[{fold:0,end:1,edge:1}],reliefEnds:[],edgeRightAngles:[2],measurementConstraints:[],pendingFold:2};}
test('edge insertion projects to outline and preserves total without pixel scaling',()=>{const state=fixture(),original=JSON.stringify(state),r=split(state,1,{x:106,y:30});assert.equal(JSON.stringify(state),original);assert.equal(r.points[2].x,100);assert.equal(r.points[2].y,30);assert.equal(r.values[1].site,null);assert.equal(r.values[2].site,null);assert.equal(r.measurementConstraints[0].value,600);assert.equal(r.measurementConstraints[0].from,1);assert.equal(r.measurementConstraints[0].to,3);assert.equal(r.markedFolds[0].to,3);assert.equal(r.rightAngles[0].edge,2);assert.equal(r.edgeRightAngles[0],3);assert.equal(r.pendingFold,3);});
test('closing edge inserts without changing point zero',()=>{const r=split(fixture(),3,{x:0,y:40});assert.equal(r.index,4);assert.equal(r.measurementConstraints[0].to,0);assert.equal(r.measurementConstraints[0].direction,-1);});
test('existing endpoints are reused',()=>{const r=split(fixture(),1,{x:100,y:100});assert.equal(r.index,1);assert.equal(r.points.length,4);});
test('one entered split measurement resolves remainder from preserved total',()=>{let r=split(fixture(),1,{x:100,y:30});r.markedFolds=[];r.rightAngles=[];r.values[1].site=150;r.values[1].manualMeasurements={site:true};const solved=c.PanelSketchComponents.infer(r.points,r.values,[],{measurementConstraints:r.measurementConstraints});assert.equal(solved.values[2].site,450);});

