const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');

test('desktop web exposes permission-aware order management',()=>{
 const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
 const client=fs.readFileSync(path.join(__dirname,'../panelstock-client.js'),'utf8');
 assert.match(html,/function OrdersPage\(\{ canCreate, canManage, isAdmin \}\)/);
 assert.match(html,/Add project/);
 assert.match(html,/\/projects/);
 assert.match(html,/Project details/);
 assert.match(html,/Project notes/);
 assert.match(html,/Delete project/);
 assert.match(html,/async function deleteProject/);
 assert.match(html,/google\.com\/maps\/search\/\?api=1&query=/);
 assert.match(html,/Open in Google Maps/);
 assert.match(html,/Open address in Google Maps/);
 assert.match(html,/GoogleMapsButtonIcon/);
 assert.match(html,/address/);
 assert.match(html,/projectRecords/);
 assert.match(html,/method: "DELETE"/);
 assert.match(html,/Delete Order/);
 assert.match(html,/changeStatus\(order, event\.target\.value\)/);
 assert.match(html,/Select a project/);
 assert.match(html,/Project order numbering/);
 assert.match(html,/Select an active project/);
 assert.match(html,/"Active project"/);
 assert.doesNotMatch(html,/order-sequence-projects/);
 assert.match(html,/\/order-sequences/);
 assert.match(html,/New projects start at Order 1/);
 assert.match(html,/site\.orders\.view/);
 assert.match(html,/site\.orders\.create/);
 assert.match(html,/site\.orders\.manage/);
 assert.match(html,/Submitted \/ Ordered/);
 assert.match(html,/Create order/);
 assert.match(html,/Save changes/);
 assert.match(html,/\/pdf-link/);
 assert.match(html,/"xlsx"/);
 assert.match(html,/window\.open\("about:blank", "_blank"\)/);
 assert.match(html,/Promise\.all\(\[ticket\(\), ticket\(\)\]\)/);
 assert.match(html,/\?download=1&ticket=/);
 assert.match(client,/taskAccess:result\.taskAccess\|\|\{\}/);
});

test('desktop dispatch uses the same material sorting as stock and damage',()=>{
 const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
 const dispatch=html.slice(html.indexOf('function DispatchPage'),html.indexOf('function DamagePage'));
 assert.match(dispatch,/ItemPicker[^\n]+sortLikeSoh: true/);
});

test('web manages the shared schedule',()=>{
 const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
 assert.match(html,/function SchedulePage\(\{ canManage,canManageCnc \}\)/);
 assert.match(html,/function ScheduleCalendarIcon/);
 assert.match(html,/New schedule entry/);
 assert.match(html,/Save schedule/);
 assert.match(html,/schedule\.view/);
 assert.match(html,/schedule\.manage/);
 assert.match(html,/BAKED_WORKER_URL\+"\/schedule"/);
 assert.match(html,/Select a person/);
 assert.match(html,/All people/);
 assert.match(html,/Orientation/);
 assert.match(html,/horizontalTimeline/);
 assert.match(html,/viewMode==="day"/);
 assert.match(html,/viewMode==="day"&&orientation==="horizontal"\?horizontalTimeline/);
 assert.match(html,/const moveDate=direction/);
 assert.match(html,/"Today"/);
 assert.match(html,/dateHeading/);
 assert.match(html,/function ScheduleTimeField/);
 assert.match(html,/function ModernDatePicker/);
 assert.match(html,/aria-label":"Previous month"/);
 assert.match(html,/aria-label":"Next month"/);
 assert.match(html,/"Select date"/);
 assert.match(html,/children:"Cancel"/);
 assert.match(html,/children:"OK"/);
 assert.match(html,/type==="date"\?e\(ModernDatePicker/);
 assert.match(html,/function ScheduleSettingsPanel/);
 assert.match(html,/BAKED_WORKER_URL\+"\/schedule\/settings"/);
 const schedule=html.slice(html.indexOf('function SchedulePage'),html.indexOf('function OrdersPage'));
 assert.doesNotMatch(schedule,/"Status"/);
 assert.ok(schedule.indexOf('"Person"')<schedule.indexOf('"Project"'));
});

test('administrators create users and the login screen has no self-registration option',()=>{
 const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
 assert.match(html,/\/admin\/create-user/);
 assert.match(html,/children:"\+ Create user"/);
 assert.match(html,/children:"Back to users"/);
 assert.match(html,/if\(createOpen\)return/);
 assert.match(html,/\/admin\/update-user/);
 assert.match(html,/children:u\.active\?"Active":"Inactive"/);
 assert.match(html,/children:u\.active\?"Deactivate":"Activate"/);
 assert.match(html,/placeholder:"e\.g\. Site Supervisor"/);
 assert.match(html,/placeholder:"e\.g\. Factory or Brisbane"/);
 assert.match(html,/\/admin\/roles/);
 assert.match(html,/children:"\+ Create role"/);
 assert.match(html,/"Save role"/);
 assert.match(html,/function RolePicker\(\{selected,onChange,disabled=false\}\)/);
 assert.match(html,/label:"Roles"/);
 assert.match(html,/roleIds:newUser\.roleIds/);
 assert.match(html,/roleIds:next\.roleIds\|\|\[\]/);
 assert.match(html,/Task access is combined from all assigned roles/);
 assert.match(html,/function EmployeeProfileFields/);
 assert.match(html,/"Employment details"/);
 assert.match(html,/"Emergency contact name"/);
 assert.match(html,/"Licences \/ qualifications"/);
 assert.match(html,/"Site inductions"/);
 assert.match(html,/"Private administrator notes"/);
 assert.match(html,/"Account history and security"/);
 assert.match(html,/employeeProfile:newUser\.employeeProfile/);
 assert.match(html,/employeeProfile:next\.employeeProfile/);
 assert.match(html,/name:"CNC tracker",codes:\["factory\.cnc","site\.cnc\.view","schedule\.cnc\.view","schedule\.cnc\.manage"\]/);
 assert.match(html,/canManageCnc:can\("schedule\.cnc\.manage"\)/);
 assert.match(html,/"Schedule type"/);
 assert.match(html,/"CNC work"/);
 assert.match(html,/name:"Schedule",codes:\["schedule\.view","schedule\.manage"\]/);
 assert.match(html,/Object\.fromEntries\(codes\.map\(code=>\[code,next\]\)\)/);
 const login=html.slice(html.indexOf('function LoginScreen'),html.indexOf('function ToggleSwitch'));
 assert.doesNotMatch(login,/children: "Register"/);
});
test('new user login names use first initial and surname',()=>{
 const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
 assert.match(html,/function loginNameFor\(displayName,excludeUsername=""\)/);
 assert.match(html,/parts\[0\]\[0\]\+parts\[parts\.length-1\]/);
 assert.match(html,/label:"Login name"/);
 assert.match(html,/readOnly:true/);
 assert.match(html,/function standardiseLogin\(user\)/);
 assert.match(html,/\/admin\/rename-user/);
 assert.match(html,/old login will work as an alias for 14 days/);
 assert.match(html,/function generateTemporaryPin\(\)/);
 assert.match(html,/crypto\.getRandomValues/);
 assert.match(html,/children:"Generate PIN"/);
 assert.match(html,/checked:newUser\.makeAdmin,disabled:busy,onChange:next/);
 assert.match(html,/title:newUser\.title,location:newUser\.location,email:newUser\.email/);
 assert.match(html,/label:"Email address \(optional\)"/);
 assert.match(html,/if\(accessUser&&editUser\)/);
 assert.match(html,/children:"Back to users"/);
});
