/* Shared desktop/mobile workshop inventory screen. */
window.createWorkshopStock = function(React) {
 const h=React.createElement, {useState,useEffect}=React;
 const categories={all:'All stock',panels:'Panel sheets',extrusions:'Extrusions',fixings:'Fixings',consumables:'Consumables',offcuts:'Offcuts'};
 const actions={receive:'Receive delivery',reserve:'Reserve for job',use:'Record usage',return:'Return from job',release:'Release reservation',damage:'Record damage',stocktake:'Stocktake count',metadata:'Edit stock details'};
 return function WorkshopStock({workerUrl,isAdmin,taskAccess={},onPanels}){
  const [data,setData]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[category,setCategory]=useState('all'),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[sort,setSort]=useState('name'),[form,setForm]=useState(null),[history,setHistory]=useState(null),[pending,setPending]=useState(null),[imageBusy,setImageBusy]=useState(false),[preview,setPreview]=useState(null);
  const pendingKey='panelstock:workshop-pending:'+PanelStock.username;
  const can=task=>isAdmin||taskAccess[task]===true;
  async function load(){try{const r=await PanelStock.apiFetch(workerUrl+'/workshop-stock'),d=await r.json();if(!r.ok)throw Error(d.error||'Workshop stock could not be loaded.');setData(d);setError('');}catch(e){setError(e.message);}}
  useEffect(()=>{load();try{const saved=JSON.parse(localStorage.getItem(pendingKey)||'null');if(saved){setPending(saved);setForm(saved.item||saved);}}catch{setError('Could not read the pending stock save. Check browser storage before editing.');}},[]);
  const change=(key,value)=>setForm(f=>({...f,[key]:value,...(key==='category'?{unit:{extrusions:'lengths',fixings:'each',consumables:'packs',offcuts:'lengths'}[value]||'each'}:{})}));
  function open(item,action){setError('');setNotice('');setPending(null);setForm({action,itemId:item?.id,quantity:action==='stocktake'?item.qty:'',job:'',reason:'',location:item?.location||'',supplier:item?.supplier||'',reorderLevel:item?.reorderLevel||0,category:'extrusions',unit:'lengths',qty:0,packSize:1,name:'',sku:'',details:'',image:item?.image||''});}
  useEffect(()=>{if(!preview)return;const close=e=>{if(e.key==='Escape')setPreview(null);};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close);},[preview]);
  async function uploadImage(event){
   const file=event.target.files?.[0];event.target.value='';if(!file)return;
   if(!['image/png','image/jpeg','image/webp'].includes(file.type)){setError('Choose a PNG, JPEG or WebP image.');return;}
   if(file.size>8*1024*1024){setError('Choose an image smaller than 8 MB.');return;}
   setImageBusy(true);setError('');let url;
   try{
    url=URL.createObjectURL(file);const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('This image could not be read.'));img.src=url;});
    if(!img.naturalWidth||img.naturalWidth*img.naturalHeight>40000000)throw Error('Choose an image under 40 megapixels.');
    const scale=Math.min(1,1600/Math.max(img.naturalWidth,img.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);
    let image=canvas.toDataURL('image/png');if(image.length>680000)image=canvas.toDataURL('image/webp',.9);if(image.length>680000)image=canvas.toDataURL('image/webp',.75);if(image.length>680000)throw Error('This image is too detailed. Choose a smaller image or crop to the profile.');
    setForm(current=>current?{...current,image}:current);
   }catch(e){setError(e.message||'The image could not be uploaded.');}finally{if(url)URL.revokeObjectURL(url);setImageBusy(false);}
  }
  async function save(e){e.preventDefault();if(imageBusy)return;setBusy(true);setError('');setNotice('');
   const payload=pending||{...(form.action==='create'?{action:'create',item:form}:form),expectedRevision:data.revision,mutationId:crypto.randomUUID()};
   try{localStorage.setItem(pendingKey,JSON.stringify(payload));}catch{setError('Browser storage is unavailable. No stock changes were sent.');setBusy(false);return;}setPending(payload);
   try{const r=await PanelStock.apiFetch(workerUrl+'/workshop-stock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok){if(r.status<500){localStorage.removeItem(pendingKey);setPending(null);}if(r.status===409)await load();throw Error(d.error||'Stock could not be saved.');}setData(d);localStorage.removeItem(pendingKey);setForm(null);setPending(null);setNotice('Stock saved.');}catch(e){setError(e.message+' If the connection failed, retry the same save to avoid duplicates.');}finally{setBusy(false);}
  }
  const field=(label,key,type='text',options)=>h('label',{className:'ws-field',key},label,options?h('select',{value:form[key],disabled:busy||imageBusy||!!pending,onChange:e=>change(key,e.target.value)},options.map(([v,t])=>h('option',{key:v,value:v},t))):h('input',{type,value:form[key]??'',disabled:busy||imageBusy||!!pending,min:type==='number'?0:undefined,step:type==='number'?'0.001':undefined,required:['name','sku','quantity','job'].includes(key),placeholder:({name:form.category==='extrusions'?'e.g. 25 × 25 aluminium angle':'e.g. Stainless rivets 4.8 mm',sku:'e.g. ANG-25-3',details:form.category==='extrusions'?'e.g. 25 × 25 × 3 mm · 6 m length · mill finish':'Size, finish or specification',location:'e.g. Rack A · Bay 2',supplier:'e.g. Knotwood',job:'Job name or reference',reason:'Add a reference or note'})[key],onChange:e=>change(key,e.target.value)}));
  const button=(label,onClick,disabled=false)=>h('button',{type:'button',onClick,disabled},label);
  const allItems=data?.items||[];
  const items=allItems.filter(i=>(category==='all'||i.category===category)&&(status==='all'||status==='reorder'&&i.available<=Number(i.reorderLevel||0)||status==='reserved'&&i.reserved>0||status==='unassigned'&&!i.location)&&[i.name,i.sku,i.location,i.supplier,i.details].join(' ').toLowerCase().includes(search.trim().toLowerCase())).sort((a,b)=>sort==='available'?a.available-b.available:sort==='location'?String(a.location||'').localeCompare(String(b.location||'')):a.name.localeCompare(b.name,undefined,{numeric:true}));
  const resetFilters=()=>{setCategory('all');setStatus('all');setSearch('');};
  const qty=value=>Number(value||0).toLocaleString('en-AU',{maximumFractionDigits:3});
  const stockStatus=item=>item.available<=0?['empty','Out of stock']:item.available<=Number(item.reorderLevel||0)?['low','Low stock']:['ok','In stock'];
  const icon=(name)=>h('svg',{width:20,height:20,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:1.6,'aria-hidden':true},h('path',{d:{box:'M3 7l9-4 9 4-9 4-9-4zm0 0v10l9 4 9-4V7M12 11v10M7 5l10 4',alert:'M12 3L2 21h20L12 3zm0 6v5m0 3v1',job:'M8 7V4h8v3M3 7h18v13H3V7zm0 6h18M10 11v4h4v-4',pin:'M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1114 0zM15 10a3 3 0 11-6 0 3 3 0 016 0',search:'M21 21l-6-6M17 10a7 7 0 11-14 0 7 7 0 0114 0',refresh:'M20 7v5h-5M4 17v-5h5M5 7a8 8 0 0114 0M19 17a8 8 0 01-14 0',plus:'M12 5v14M5 12h14'}[name]}));
  const metric=(key,label,value,caption,symbol)=>h('button',{type:'button',className:'ws-metric '+(status===key?'is-selected':''),'aria-pressed':status===key,onClick:()=>{setCategory('all');setSearch('');setStatus(status===key?'all':key);}},h('span',{className:'ws-metric-top'},label,h('span',{className:'ws-metric-icon '+key},icon(symbol))),h('strong',null,value),h('small',null,caption));
  const selected=data?.items.find(i=>i.id===form?.itemId);
  function allowed(action){return ['create','metadata','stocktake'].includes(action)?isAdmin:can(action==='damage'?'factory.damage':['receive','return'].includes(action)?'factory.receive':'factory.dispatch');}
  const imageEditor=()=>h('div',{className:'ws-image-editor'},h('div',{className:'ws-image-edit-preview'},form.image?h('img',{src:form.image,alt:'Selected stock profile'}):icon('box')),h('div',null,h('strong',null,'Profile / item image'),h('p',null,'Add a profile drawing or product photo. PNG, JPG or WebP, up to 8 MB.'),h('div',{className:'ws-image-controls'},h('label',{className:'ws-upload '+(busy||imageBusy||pending?'is-disabled':'')},h('input',{type:'file',accept:'image/png,image/jpeg,image/webp','aria-label':'Profile or item image',disabled:busy||imageBusy||!!pending,onChange:uploadImage}),imageBusy?'Preparing image…':form.image?'Replace image':'Choose image'),form.image&&button('Remove image',()=>change('image',''),busy||imageBusy||!!pending)),h('small',null,'The image is saved when you save this item.')));
  return h('section',{className:'ws'},
   h('div',{className:'ws-heading'},h('div',null,h('div',{className:'ws-eyebrow'},'INVENTORY / WORKSHOP'),h('h2',null,'Workshop stock'),h('p',null,'Know what’s available, what’s allocated and what needs restocking.')),h('div',{className:'ws-actions'},h('button',{type:'button',onClick:load,disabled:busy,className:'ws-refresh'},icon('refresh'),'Refresh'),isAdmin&&h('button',{type:'button',className:'ws-primary',onClick:()=>open(null,'create'),disabled:busy},icon('plus'),'Add stock item'))),
   error&&h('div',{className:'ws-error',role:'alert'},error),notice&&h('div',{className:'ws-notice',role:'status'},notice),
   !data?h('p',null,'Loading workshop stock…'):h(React.Fragment,null,
    h('div',{className:'ws-summary'},metric('all','Stock items',allItems.length,'Across all categories','box'),metric('reorder','Needs restocking',allItems.filter(i=>i.available<=Number(i.reorderLevel||0)).length,'At or below reorder level','alert'),metric('reserved','Allocated to jobs',allItems.filter(i=>i.reserved>0).length,'Items with reserved stock','job'),metric('unassigned','Location needed',allItems.filter(i=>!i.location).length,'Assign a rack, shelf or bin','pin')),
    h('div',{className:'ws-inventory'},
     h('div',{className:'ws-tabs',role:'group','aria-label':'Stock categories'},Object.entries(categories).map(([key,label])=>h('button',{type:'button',key,className:category===key?'is-active':'','aria-pressed':category===key,onClick:()=>setCategory(key)},label,h('span',null,key==='all'?allItems.length:allItems.filter(i=>i.category===key).length)))),
     h('div',{className:'ws-filters'},h('label',{className:'ws-search'},icon('search'),h('input',{'aria-label':'Search stock',value:search,placeholder:'Search by item, code, location or supplier…',onChange:e=>setSearch(e.target.value)})),h('select',{'aria-label':'Stock status',value:status,onChange:e=>setStatus(e.target.value)},[['all','All statuses'],['reorder','Needs restocking'],['reserved','Allocated to jobs'],['unassigned','Location needed']].map(([v,t])=>h('option',{value:v,key:v},t))),h('select',{'aria-label':'Sort stock',value:sort,onChange:e=>setSort(e.target.value)},[['name','Sort: item name'],['available','Sort: lowest available'],['location','Sort: location']].map(([v,t])=>h('option',{value:v,key:v},t)))),
     h('div',{className:'ws-list-caption'},h('span',null,h('strong',null,categories[category]),' · '+items.length+' '+(items.length===1?'item':'items')), (status!=='all'||search||category!=='all')&&button('Clear filters',resetFilters)),
     h('div',{className:'ws-table'},h('table',null,h('thead',null,h('tr',null,['Stock item','Location','On hand','Reserved','Available','Reorder at','Status','Actions'].map(t=>h('th',{key:t},t)))),h('tbody',null,items.map(item=>{
      const [tone,label]=stockStatus(item);
      const name=item.legacy&&item.color&&item.material?item.color+' · '+item.material:item.name;
      const detail=item.legacy&&item.width?item.thickness+' mm · '+item.width+' × '+item.height+' mm':item.details;
      return h('tr',{key:item.id},
       h('td',null,h('div',{className:'ws-product'},item.image?h('button',{type:'button',className:'ws-thumbnail','aria-label':'View image for '+item.name,onClick:()=>setPreview(item)},h('img',{src:item.image,alt:item.name+' profile',loading:'lazy'})):h('span',{className:'ws-product-icon'},icon('box')),h('div',null,h('strong',null,name),detail&&h('small',{className:'ws-spec'},detail),h('div',{className:'ws-item-meta'},h('span',{className:'ws-sku'},item.sku||'No code'),h('span',null,categories[item.category]))))),
       h('td',null,item.location?h('span',{className:'ws-location'},icon('pin'),item.location):isAdmin?h('button',{type:'button',className:'ws-location-add',onClick:()=>open(item,'metadata')},'+ Add location'):h('span',{className:'ws-muted'},'Not assigned')),
       h('td',{className:'ws-number'},qty(item.qty),h('small',null,item.unit)),
       h('td',{className:'ws-number'},item.reserved>0?h('span',{className:'ws-reserved'},qty(item.reserved)):h('span',{className:'ws-muted'},'—')),
       h('td',{className:'ws-number ws-available '+tone},qty(item.available)),
       h('td',{className:'ws-number'},Number(item.reorderLevel)>0?qty(item.reorderLevel):h('span',{className:'ws-muted',title:'No minimum stock level set'},'—')),
       h('td',null,h('span',{className:'ws-badge '+tone},h('i',null),label)),
       h('td',null,h('select',{className:'ws-action-select','aria-label':'Stock action for '+item.name,value:'',onChange:e=>{const action=e.target.value;if(action==='panels')onPanels();else if(action==='history')setHistory(item.id);else if(action)open(item,action);}},h('option',{value:''},'Manage'),item.legacy?h(React.Fragment,null,h('option',{value:'panels'},'Open panel stock'),isAdmin&&h('option',{value:'metadata'},'Edit details')):h(React.Fragment,null,Object.entries(actions).filter(([a])=>allowed(a)).map(([a,t])=>h('option',{key:a,value:a},t)),h('option',{value:'history'},'View history')))));
     })))),
     !items.length&&h('div',{className:'ws-empty'},icon('box'),h('h3',null,allItems.length?'No matching stock':'Start your workshop inventory'),h('p',null,allItems.length?'Try a different search or clear your filters.':'Add your first item with an opening quantity and storage location.'),allItems.length?button('Clear filters',resetFilters):isAdmin&&button('Add stock item',()=>open(null,'create'))),
     h('div',{className:'ws-table-footer'},'Quantities are shown in each item’s stock unit.',h('span',null,'Available = on hand − reserved'))
    ),
    h('details',{className:'ws-help'},h('summary',null,'How stock and allocations work'),h('p',null,'CNC scheduling reserves panel sheets automatically. Use the panel stock screens for sheets and sheet offcuts. Reserve other stock against a job here, then record usage when the material is used. Release unused allocations to make stock available again.')),
    history&&h('div',{className:'ws-history'},h('div',{className:'ws-heading'},h('h3',null,'Movement history'),button('Close',()=>setHistory(null))),h('p',null,'Current reservations: '+Object.entries(data.items.find(i=>i.id===history)?.reservations||{}).filter(([,q])=>q>0).map(([job,q])=>job+': '+q).join(', ')),data.movements.filter(m=>m.itemId===history).map(m=>h('p',{key:m.id},new Date(m.at).toLocaleString('en-AU')+' · '+m.action+' · '+m.quantity+' · '+m.user+(m.job?' · '+m.job:'')+(m.reason?' · '+m.reason:''))))
   ),
   form&&h('div',{className:'ws-overlay'},h('form',{className:'ws-dialog '+(form.action==='create'?'ws-create-dialog':''),onSubmit:save,role:'dialog','aria-modal':true,'aria-label':form.action==='create'?'Add stock item':actions[form.action]},h('div',{className:'ws-form-heading'},h('span',{className:'ws-eyebrow'},form.action==='create'?'WORKSHOP INVENTORY':'STOCK DETAILS'),h('h3',null,form.action==='create'?'Add stock item':actions[form.action]),form.action==='create'&&h('p',null,'Set up the item, add its profile and record your starting stock.')),selected&&h('p',null,selected.name+' · '+selected.unit),
    form.action==='create'?h('div',{className:'ws-create-content'},
     h('div',{className:'ws-create-top'},h('section',{className:'ws-form-section'},h('h4',null,'01',h('span',null,'Item details')),h('div',{className:'ws-fields'},field('Category','category','text',Object.entries(categories).filter(([k])=>['extrusions','fixings','consumables','offcuts'].includes(k))),field('Stock code','sku'),field(form.category==='extrusions'?'Profile name':'Item name','name'),field('Supplier','supplier'),h('div',{className:'ws-full-field'},field(form.category==='offcuts'?'Profile / remaining dimensions (required)':form.category==='extrusions'?'Profile size, length & finish':'Size / finish / specification','details')))),h('section',{className:'ws-form-section ws-profile-section'},h('h4',null,'02',h('span',null,'Profile image')),imageEditor())),
     h('section',{className:'ws-form-section ws-stock-section'},h('h4',null,'03',h('span',null,'Stock & storage')),h('div',{className:'ws-fields'},field('Stock unit','unit','text',['lengths','each','boxes','packs','rolls','tubes','litres','metres','kg'].map(v=>[v,v.charAt(0).toUpperCase()+v.slice(1)])),field('Opening quantity ('+form.unit+')','qty','number'),field('Reorder level ('+form.unit+')','reorderLevel','number'),field('Rack / shelf / bin','location'),['boxes','packs'].includes(form.unit)&&field('Units per pack (reference only)','packSize','number')),h('p',{className:'ws-field-hint'},'Opening quantity is what you have in the workshop now. Reorder level flags when available stock runs low.'))):
    form.action==='metadata'?h('div',{className:'ws-fields'},field('Rack / shelf / bin','location'),field('Supplier','supplier'),field('Reorder level','reorderLevel','number')):
    h('div',{className:'ws-fields'},field(form.action==='stocktake'?'Actual counted quantity':'Quantity','quantity','number'),['use','return','reserve','release'].includes(form.action)&&field('Job reference','job'),field(['damage','stocktake'].includes(form.action)?'Reason (required)':'Delivery reference / notes','reason')),
    form.action==='metadata'&&imageEditor(),
    selected?.reservations&&h('p',null,'Reservations: '+Object.entries(selected.reservations).filter(([,q])=>q>0).map(([j,q])=>j+': '+q).join(', ')),
    error&&h('div',{className:'ws-error',role:'alert'},error),pending&&!busy&&h('p',null,'Save status is uncertain. Retry this unchanged request before starting another movement.'),
    h('div',{className:'ws-actions'},button('Cancel',()=>setForm(null),busy||imageBusy||!!pending),h('button',{type:'submit',disabled:busy||imageBusy},imageBusy?'Preparing image…':busy?'Saving…':pending?'Retry save':form.action==='create'?'Create stock item':'Save')))),
   preview&&h('div',{className:'ws-overlay',onClick:e=>{if(e.target===e.currentTarget)setPreview(null);}},h('div',{className:'ws-dialog ws-image-viewer',role:'dialog','aria-modal':true,'aria-label':'Stock image'},h('div',{className:'ws-heading'},h('div',null,h('h3',null,preview.name),h('p',null,preview.sku)),h('button',{type:'button',autoFocus:true,onClick:()=>setPreview(null),'aria-label':'Close image'},'Close')),h('img',{src:preview.image,alt:preview.name+' profile'})))
  );
 };
};
