/* Keep wheel gestures from changing a focused numeric value. */
if(typeof document!=='undefined')document.addEventListener('wheel',event=>{
 const input=event.target;
 if(input?.tagName==='INPUT'&&input.type==='number'&&document.activeElement===input)event.preventDefault();
},{capture:true,passive:false});

/* Shared desktop/mobile workshop inventory screen. */
window.createWorkshopStock = function(React) {
 const h=React.createElement, {useState,useEffect}=React;
 const PurchaseOrderReceiving=window.createPurchaseOrderReceiving(React);
 const defaultCategories={all:'All Stock',panels:'Panels',extrusions:'Extrusions',fixings:'Fixings',consumables:'Consumables',offcuts:'Offcuts'};
 const actions={receive:'Receive delivery',reserve:'Reserve for job',use:'Record usage',return:'Return from job',release:'Release reservation',damage:'Record damage',stocktake:'Stocktake count',metadata:'Edit stock details',category_save:'Manage categories',stocktake_create:'Create stocktake',bulk_metadata:'Bulk edit stock'};
 return function WorkshopStock({workerUrl,isAdmin,taskAccess={},onPanels,onAddOffcut,onExportExcel,onExportPDF,stockRevision}){
  const [data,setData]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[category,setCategory]=useState('all'),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[sort,setSort]=useState('name'),[form,setForm]=useState(null),[history,setHistory]=useState(null),[pending,setPending]=useState(null),[imageBusy,setImageBusy]=useState(false),[preview,setPreview]=useState(null),[enhanceOutline,setEnhanceOutline]=useState(false);
  const [poOpen,setPoOpen]=useState(false),[selectedIds,setSelectedIds]=useState([]);
  const [stockArea,setStockArea]=useState('stock');
  const [restockFilter,setRestockFilter]=useState('all'),[restockSearch,setRestockSearch]=useState(''),[restockPage,setRestockPage]=useState(0);
  const labels={...defaultCategories,...data?.categories};
  if(labels.panels==='Panel sheets')labels.panels='Panels';
  for(const [key,label] of [['steel','Steel'],['other','Other']])if(!Object.hasOwn(labels,key)&&!Object.values(labels).some(v=>String(v).trim().toLowerCase()===key))labels[key]=label;
  const order=['all','panels','offcuts','extrusions','steel','fixings','consumables','other'];
  const rank=([key,label])=>{const canonical=['steel','other'].includes(String(label).trim().toLowerCase())?String(label).trim().toLowerCase():key;const i=order.indexOf(canonical);return i<0?order.length:i;};
  const categories=Object.fromEntries(Object.entries(labels).sort((a,b)=>rank(a)-rank(b)));

  const [countList,setCountList]=useState(false),[countId,setCountId]=useState(null);
  const activeCount=(data?.stocktakes||[]).find(c=>c.id===countId);
  const countKey='panelstock:stocktake:'+PanelStock.username+':'+countId;
  const [countFilter,setCountFilter]=useState('all'),[countActive,setCountActive]=useState(null),[counting,setCounting]=useState(false),[review,setReview]=useState(false),[countSearch,setCountSearch]=useState(''),[countLocation,setCountLocation]=useState(''),[countDraft,setCountDraft]=useState(()=>{try{return JSON.parse(localStorage.getItem(countKey))||{counts:{},reference:''};}catch{return {counts:{},reference:''};}});
  function updateCountDraft(next){try{localStorage.setItem(countKey,JSON.stringify(next));setCountDraft(next);setError('');}catch{setError('Could not save counts on this device. Free browser storage before continuing.');}}
  function startCount(count){
   let draft={counts:{},reference:count.name};
   try{draft=JSON.parse(localStorage.getItem('panelstock:stocktake:'+PanelStock.username+':'+count.id))||draft;}catch{}
   if(!draft.request)draft.counts=Object.fromEntries(Object.entries(draft.counts).filter(([id])=>count.itemIds.includes(id)&&!Object.hasOwn(count.counts,id)));
   setCountId(count.id);setCountDraft(draft);setCountList(false);setCounting(true);setReview(false);setCountSearch('');setCountLocation('');setCountFilter('all');setError('');
  }
  function enterCount(item,value){updateCountDraft({...countDraft,counts:{...countDraft.counts,[item.id]:{quantity:value,expectedQty:item.qty}}});}
  async function submitCounts(){
   setBusy(true);setError('');
   const payload=countDraft.request||{action:'stocktake_batch',stocktakeId:countId,counts:Object.entries(countDraft.counts).filter(([id,c])=>c.quantity!==''&&countItems.some(i=>i.id===id)).map(([itemId,c])=>({itemId,quantity:c.quantity,expectedQty:c.expectedQty})),reason:countDraft.reference,expectedRevision:data.revision,mutationId:crypto.randomUUID()};
   try{localStorage.setItem(countKey,JSON.stringify({...countDraft,request:payload}));setCountDraft({...countDraft,request:payload});
    const r=await PanelStock.apiFetch(workerUrl+'/workshop-stock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json();
    if(!r.ok){if(r.status<500){const next={...countDraft};delete next.request;localStorage.setItem(countKey,JSON.stringify(next));setCountDraft(next);}if(r.status===409)await load();throw Error(d.error||'Counts could not be saved.');}
    localStorage.removeItem(countKey);setCountDraft({counts:{},reference:''});setData(d);setCounting(false);setCountList(true);setReview(false);setNotice('Stocktake saved. Quantities and movement history updated.');
   }catch(e){setError(e.message);}finally{setBusy(false);}
  }
  const pendingKey='panelstock:workshop-pending:'+PanelStock.username;
  const can=task=>isAdmin||taskAccess[task]===true;
  async function load(){try{const r=await PanelStock.apiFetch(workerUrl+'/workshop-stock'),d=await r.json();if(!r.ok)throw Error(d.error||'Workshop stock could not be loaded.');setData(d);setError('');}catch(e){setError(e.message);}}
  useEffect(()=>{load();},[stockRevision]);
  useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(pendingKey)||'null');if(saved){setPending(saved);setForm(saved.item||saved);}}catch{setError('Could not read the pending stock save. Check browser storage before editing.');}},[]);
  const change=(key,value)=>setForm(f=>({...f,[key]:value,...(key==='categoryId'?{name:value?categories[value]:''}:{}),...(key==='sku'&&f.action==='create'?(()=>{const p=(data?.items||[]).find(i=>!i.legacy&&String(i.sku).trim().replace(/\s+/g,' ').toLowerCase()===String(value).trim().replace(/\s+/g,' ').toLowerCase());return p?{category:p.category,unit:p.unit,name:p.name,dimensions:p.dimensions||'',image:p.image||''}:{};})():{}),...(key==='category'?{unit:{extrusions:'lengths',fixings:'each',consumables:'packs',offcuts:'lengths'}[value]||'each'}:{})}));
  function open(item,action){const variant=action==='variant';if(variant)action='create';setError('');setNotice('');setPending(null);setForm({action,variant,categoryId:'',catalogId:item?.legacy&&item.category==='offcuts'?item.catalogId||'':undefined,expectedMaterial:item?.legacy?JSON.stringify([item.catalogId||'',item.color,item.material,Number(item.thickness)]):undefined,itemId:variant?undefined:item?.id,quantity:action==='stocktake'?item.qty:'',job:'',reason:'',location:item?.location||'',supplier:item?.supplier||'',reorderLevel:item?.reorderLevel||0,category:item?.category||'extrusions',unit:item?.unit||'lengths',qty:0,packSize:item?.packSize||1,name:item?.name||'',sku:variant?item.sku:'',details:item?.details||'',lengthMm:item?.lengthMm??'',dimensions:item?.dimensions||'',colour:variant?'':item?.colour||'',image:item?.image||''});}
  useEffect(()=>{if(!preview)return;const close=e=>{if(e.key==='Escape')setPreview(null);};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close);},[preview]);
  async function uploadImage(event){
   const file=event.target.files?.[0];event.target.value='';if(!file)return;
   if(!['image/png','image/jpeg','image/webp'].includes(file.type)){setError('Choose a PNG, JPEG or WebP image.');return;}
   if(file.size>8*1024*1024){setError('Choose an image smaller than 8 MB.');return;}
   setImageBusy(true);setError('');let url;
   try{
    url=URL.createObjectURL(file);const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('This image could not be read.'));img.src=url;});
    if(!img.naturalWidth||img.naturalWidth*img.naturalHeight>40000000)throw Error('Choose an image under 40 megapixels.');
    const scale=Math.min(1,1600/Math.max(img.naturalWidth,img.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);
    let image=canvas.toDataURL('image/png');if(image.length>680000)image=canvas.toDataURL('image/webp',.9);if(image.length>680000)image=canvas.toDataURL('image/webp',.75);if(image.length>680000)throw Error('This image is too detailed. Choose a smaller image or crop to the profile.');
    setForm(current=>current?{...current,image}:current);
   }catch(e){setError(e.message||'The image could not be uploaded.');}finally{if(url)URL.revokeObjectURL(url);setImageBusy(false);}
  }
  async function save(e){e.preventDefault();if(imageBusy)return;setBusy(true);setError('');setNotice('');
   const payload=pending||{...(form.action==='create'?{action:'create',item:form}:form),expectedRevision:data.revision,mutationId:crypto.randomUUID()};
   try{localStorage.setItem(pendingKey,JSON.stringify(payload));}catch{setError('Browser storage is unavailable. No stock changes were sent.');setBusy(false);return;}setPending(payload);
   try{const r=await PanelStock.apiFetch(workerUrl+'/workshop-stock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok){if(r.status<500){localStorage.removeItem(pendingKey);setPending(null);}if(r.status===409)await load();throw Error(d.error||'Stock could not be saved.');}setData(d);localStorage.removeItem(pendingKey);setForm(null);setPending(null);setNotice(form.action==='stocktake_create'?'Stocktake created. Workers can now select it.':form.action==='bulk_metadata'?'Updated '+form.itemIds.length+' stock items.':'Stock saved.');if(form.action==='bulk_metadata')setSelectedIds([]);if(form.action==='stocktake_create')setCountList(true);}catch(e){setError(e.message+' If the connection failed, retry the same save to avoid duplicates.');}finally{setBusy(false);}
  }
  const field=(label,key,type='text',options)=>h('label',{className:'ws-field',key},label,options?h('select',{value:form[key],disabled:busy||imageBusy||!!pending||!!(sharedProfile&&['category','unit'].includes(key)),onChange:e=>change(key,e.target.value)},options.map(([v,t])=>h('option',{key:v,value:v},t))):h('input',{type,value:sharedProfile&&['name','dimensions'].includes(key)?sharedProfile[key]||'':form[key]??'',disabled:busy||imageBusy||!!pending||!!(sharedProfile&&['name','dimensions'].includes(key)),min:type==='number'?0:undefined,step:type==='number'?'0.001':undefined,required:['name','sku','quantity','job'].includes(key),placeholder:({name:form.category==='extrusions'?'e.g. 25 × 25 aluminium angle':'e.g. Stainless rivets 4.8 mm',sku:'e.g. ANG-25-3',lengthMm:'e.g. 6000',dimensions:'e.g. 80 × 40 × 3 mm',colour:'e.g. Black, mill finish or timber grain',details:'Additional notes (optional)',location:'e.g. Rack A · Bay 2',supplier:'e.g. Knotwood',job:'Job name or reference',reason:'Add a reference or note'})[key],onChange:e=>change(key,e.target.value)}));
  const button=(label,onClick,disabled=false)=>h('button',{type:'button',onClick,disabled},label);
  const allItems=data?.items||[];
  const items=allItems.filter(i=>(category==='all'||i.category===category)&&(status==='all'||status==='reorder'&&i.available<=Number(i.reorderLevel||0)||status==='reserved'&&i.reserved>0||status==='unassigned'&&!i.location)&&[i.name,i.sku,i.location,i.supplier,i.details,i.lengthMm,i.dimensions,i.colour].join(' ').toLowerCase().includes(search.trim().toLowerCase())).sort((a,b)=>sort==='available'?a.available-b.available:sort==='location'?String(a.location||'').localeCompare(String(b.location||'')):a.name.localeCompare(b.name,undefined,{numeric:true}));
  const lowItems=allItems.filter(i=>i.available<=Number(i.reorderLevel||0)).sort((a,b)=>(a.available>0)-(b.available>0)||a.name.localeCompare(b.name,undefined,{numeric:true}));
  const shortfall=i=>Math.max(0,Math.round((Number(i.reorderLevel||0)-i.available-Number(i.onOrder||0))*1000)/1000);
  const waitingItems=lowItems.filter(i=>Number(i.onOrder)>0);
  const noMinimum=lowItems.filter(i=>!(Number(i.reorderLevel)>0));
  const reviewItems=lowItems.filter(i=>Number(i.reorderLevel)>0&&(shortfall(i)>0||!Number(i.onOrder)));
  const restockMatches=lowItems.filter(i=>(restockFilter==='all'||restockFilter==='review'&&reviewItems.includes(i)||restockFilter==='waiting'&&Number(i.onOrder)>0||restockFilter==='setup'&&!(Number(i.reorderLevel)>0))&&[i.name,i.sku,i.colour,i.dimensions,i.lengthMm,i.supplier].join(' ').toLowerCase().includes(restockSearch.trim().toLowerCase()));
  const restockPages=Math.max(1,Math.ceil(restockMatches.length/8)),currentRestockPage=Math.min(restockPage,restockPages-1);
  const restockRows=restockMatches.slice(currentRestockPage*8,currentRestockPage*8+8);
  const selectedStock=allItems.filter(i=>selectedIds.includes(i.id));
  function toggleSelected(id,checked){setSelectedIds(ids=>checked?[...new Set([...ids,id])]:ids.filter(value=>value!==id));}
  function openBulk(){setError('');setNotice('');setForm({action:'bulk_metadata',itemIds:selectedStock.map(i=>i.id),changes:{}});}
  const bulkHasPanels=form?.action==='bulk_metadata'&&allItems.some(i=>form.itemIds.includes(i.id)&&i.legacy);
  const bulkFields=[['name','Stock item name','text'],['category','Category','select'],['location','Rack / shelf / bin','text'],['supplier','Supplier','text'],['reorderLevel','Reorder level','number'],['colour','Colour / finish','text'],['lengthMm','Length (mm)','number'],['dimensions','Dimensions / profile size','text']];
  function bulkChange(key,value){setForm(f=>({...f,changes:{...f.changes,[key]:value}}));}
  const resetFilters=()=>{setCategory('all');setStatus('all');setSearch('');};
  const qty=value=>Number(value||0).toLocaleString('en-AU',{maximumFractionDigits:3});
  const stockStatus=item=>item.available<=0?['empty','Out of stock']:item.available<=Number(item.reorderLevel||0)?['low','Low stock']:['ok','In stock'];
  const icon=(name)=>h('svg',{width:20,height:20,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:1.6,'aria-hidden':true},h('path',{d:{box:'M3 7l9-4 9 4-9 4-9-4zm0 0v10l9 4 9-4V7M12 11v10M7 5l10 4',alert:'M12 3L2 21h20L12 3zm0 6v5m0 3v1',job:'M8 7V4h8v3M3 7h18v13H3V7zm0 6h18M10 11v4h4v-4',pin:'M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1114 0zM15 10a3 3 0 11-6 0 3 3 0 016 0',search:'M21 21l-6-6M17 10a7 7 0 11-14 0 7 7 0 0114 0',refresh:'M20 7v5h-5M4 17v-5h5M5 7a8 8 0 0114 0M19 17a8 8 0 01-14 0',excel:'M4 3h16v18H4zM4 9h16M4 15h16M10 9v12',pdf:'M14 2H5v20h14V7zM14 2v5h5M12 10v8m-3-3 3 3 3-3',offcut:'M3 3h12v7h6v11H3zM7 14h6m-3-3v6',plus:'M12 5v14M5 12h14'}[name]}));
  const iconButton=(label,symbol,onClick)=>h('button',{type:'button',className:'ws-icon-button',title:label,'aria-label':label,onClick},icon(symbol));
  const metric=(key,label,value,caption,symbol)=>h('button',{type:'button',className:'ws-metric '+((stockArea==='restock'?key==='reorder':key!=='reorder'&&status===key)?'is-selected':''),'aria-pressed':stockArea==='restock'?key==='reorder':key!=='reorder'&&status===key,onClick:()=>{setStockArea(key==='reorder'?'restock':'stock');setCategory('all');setSearch('');setStatus(key==='reorder'?'all':status===key?'all':key);}},h('span',{className:'ws-metric-top'},label,h('span',{className:'ws-metric-icon '+key},icon(symbol))),h('strong',null,value),h('small',null,caption));
  const profileKey=v=>String(v||'').trim().replace(/\s+/g,' ').toLowerCase();
  const sharedProfile=form?.action==='create'?allItems.find(i=>!i.legacy&&profileKey(i.sku)===profileKey(form.sku)):null;
  const profileVariants=selectedItem=>allItems.filter(i=>!i.legacy&&profileKey(i.sku)===profileKey(selectedItem?.sku)).length;
  const countItems=allItems.filter(i=>!i.legacy&&activeCount?.itemIds.includes(i.id)&&!Object.hasOwn(activeCount.counts,i.id));
  const hasCount=i=>countDraft.counts[i.id]?.quantity!==undefined&&countDraft.counts[i.id]?.quantity!=='';
  const countedTotal=countItems.filter(hasCount).length;
  const visibleCounts=countItems.filter(i=>review?hasCount(i):(!countLocation||(i.location||'Unassigned')===countLocation)&&[i.name,i.sku,i.colour,i.lengthMm,i.dimensions].join(' ').toLowerCase().includes(countSearch.toLowerCase())&&(countFilter==='all'||!hasCount(i)||countActive===i.id)).sort((a,b)=>String(a.location||'').localeCompare(String(b.location||''))||a.sku.localeCompare(b.sku)||String(a.colour||'').localeCompare(String(b.colour||'')));
  const selected=data?.items.find(i=>i.id===form?.itemId);
  function allowed(action){return ['create','metadata','stocktake'].includes(action)?isAdmin:can(action==='damage'?'factory.damage':['receive','return'].includes(action)?'factory.receive':'factory.dispatch');}
  const imageEditor=()=>sharedProfile?h('div',{className:'ws-image-editor'},h('div',{className:'ws-image-edit-preview'},sharedProfile.image?h('img',{src:sharedProfile.image,alt:'Shared stock profile'}):icon('box')),h('p',null,'Uses the existing profile image and dimensions. Edit stock details to update them for all variants.')):h('div',{className:'ws-image-editor'},h('div',{className:'ws-image-edit-preview'},form.image?h('img',{src:form.image,alt:'Selected stock profile'}):icon('box')),h('div',null,h('strong',null,'Profile / item image'),h('p',null,'Add a profile drawing or product photo. PNG, JPG or WebP, up to 8 MB.'),h('div',{className:'ws-image-controls'},h('label',{className:'ws-upload '+(busy||imageBusy||pending?'is-disabled':'')},h('input',{type:'file',accept:'image/png,image/jpeg,image/webp','aria-label':'Profile or item image',disabled:busy||imageBusy||!!pending,onChange:uploadImage}),imageBusy?'Preparing image…':form.image?'Replace image':'Choose image'),form.image&&button('Remove image',()=>change('image',''),busy||imageBusy||!!pending)),h('small',null,'The image is saved when you save this item.')));
  return h('section',{className:'ws'},
   h('div',{className:'ws-heading ws-stock-heading'},h('div',null,h('div',{className:'ws-eyebrow'},'INVENTORY / STOCK ON HAND'),h('h2',null,'SOH'),h('p',null,'Know what’s available, what’s allocated and what needs restocking.')),h('div',{className:'ws-actions ws-stock-actions'},h('button',{type:'button',onClick:load,disabled:busy,className:'ws-refresh'},icon('refresh'),'Refresh'),isAdmin&&h('button',{type:'button',className:'ws-manage-categories',onClick:()=>open(null,'category_save'),disabled:busy||!!pending},'Manage categories'),can('factory.receive')&&h('button',{type:'button',className:'ws-receive-po',onClick:()=>setPoOpen(true)},'Receive against PO'),can('factory.stock')&&h('button',{type:'button',className:'ws-start-stocktake',onClick:()=>{setCountList(true);setError('');load();},disabled:busy||!!pending},'Stocktake'),isAdmin&&h('button',{type:'button',className:'ws-primary',onClick:()=>open(null,'create'),disabled:busy},icon('plus'),'Add stock item'))),
   error&&h('div',{className:'ws-error',role:'alert'},error),notice&&h('div',{className:'ws-notice',role:'status'},notice),
   !data?h('p',null,'Loading workshop stock…'):h(React.Fragment,null,
    h('div',{className:'ws-summary'},metric('all','Stock items',allItems.length,'Across all categories','box'),metric('reorder','Needs restocking',allItems.filter(i=>i.available<=Number(i.reorderLevel||0)).length,'At or below reorder level','alert'),metric('reserved','Allocated to jobs',allItems.filter(i=>i.reserved>0).length,'Items with reserved stock','job'),metric('unassigned','Location needed',allItems.filter(i=>!i.location).length,'Assign a rack, shelf or bin','pin')),
    stockArea==='restock'&&h('section',{className:'ws-restock','aria-label':'Restocking overview'},
     h('div',{className:'ws-restock-heading'},h('h3',null,'Restocking'),h('p',null,lowItems.length+' low-stock items · '+waitingItems.length+' awaiting deliveries · '+reviewItems.length+' to review · '+noMinimum.length+' need a reorder level')),
     h('div',{className:'ws-restock-tools'},h('div',{className:'ws-restock-filters',role:'group','aria-label':'Restocking filters'},[['all','All',lowItems.length],['review','To review',reviewItems.length],['waiting','On order',waitingItems.length],['setup','Set reorder level',noMinimum.length]].map(([value,label,count])=>h('button',{type:'button',key:value,'aria-pressed':restockFilter===value,onClick:()=>{setRestockFilter(value);setRestockPage(0);}},label,h('span',null,count)))),h('input',{'aria-label':'Search restocking items',placeholder:'Search item, code or supplier…',value:restockSearch,onChange:e=>{setRestockSearch(e.target.value);setRestockPage(0);}})),
     !restockMatches.length?h('p',{className:'ws-notice'},lowItems.length?'No items match this filter or search.':'No items are at or below their reorder level.'):h('div',{className:'ws-restock-list'},restockRows.map(i=>h('article',{className:'ws-restock-item',key:i.id},
      h('div',{className:'ws-restock-identity'},
       i.legacy&&i.colorHex?h('span',{className:'ws-restock-picture ws-panel-swatch',role:'img','aria-label':i.color||i.name,style:{backgroundColor:i.colorHex}}):i.image?h('button',{type:'button',className:'ws-restock-picture','aria-label':'View profile for '+i.name,onClick:()=>setPreview(i)},h('img',{src:i.image,alt:i.name+' profile',loading:'lazy'})):h('span',{className:'ws-restock-picture ws-restock-placeholder','aria-hidden':true},icon('box')),
       h('div',{className:'ws-restock-description'},h('div',{className:'ws-restock-title'},h('strong',null,i.name),h('span',{className:'ws-badge '+(i.available<=0?'empty':'low')},i.available<=0?'Out of stock':'Low stock')),h('div',{className:'ws-restock-specs'},i.sku&&h('span',{className:'ws-sku'},i.sku),h('span',null,[i.colour||i.color,i.lengthMm?i.lengthMm+' mm':null,i.dimensions|| (i.legacy&&i.width?i.width+' × '+i.height+' mm':null)].filter(Boolean).join(' · '))),h('small',{className:'ws-restock-unit'},[i.supplier,i.unit].filter(Boolean).join(' · ')))),
      h('dl',null,[['Available',i.available],['Reorder at',Number(i.reorderLevel)>0?i.reorderLevel:null],['On order',i.onOrder||0],['Shortfall',Number(i.reorderLevel)>0?shortfall(i):null]].map(([label,value])=>h('div',{key:label,className:label==='Shortfall'&&value>0?'ws-restock-gap':''},h('dt',null,label),h('dd',{title:value===null?'Set a reorder level to calculate this':undefined},value===null?'—':qty(value))))),
      h('div',{className:'ws-restock-next'},h('span',null,!(Number(i.reorderLevel)>0)?'No reorder level set':Number(i.onOrder)>0?(shortfall(i)>0?'More stock needed':'Awaiting delivery'):shortfall(i)>0?'Review replenishment':'At reorder point'),isAdmin&&button(Number(i.reorderLevel)>0?'Edit level':'Set reorder level',()=>open(i,'metadata')))
     ))),
     h('div',{className:'ws-restock-footer'},h('span',{role:'status'},restockMatches.length?'Showing '+(currentRestockPage*8+1)+'–'+Math.min((currentRestockPage+1)*8,restockMatches.length)+' of '+restockMatches.length+' items':'0 items'),restockPages>1&&h('div',{className:'ws-restock-pagination'},button('Previous',()=>setRestockPage(currentRestockPage-1),currentRestockPage===0),h('span',null,(currentRestockPage+1)+' / '+restockPages),button('Next',()=>setRestockPage(currentRestockPage+1),currentRestockPage===restockPages-1)),can('factory.receive')&&button('Open purchase orders',()=>setPoOpen(true))),
     h('p',{className:'ws-restock-help'},'On order = outstanding on open POs. Shortfall = amount below the reorder level after incoming stock. Quantities use the item’s stock unit.')
    ),
    stockArea==='stock'&&h(React.Fragment,null,
    h('div',{className:'ws-actions',style:{marginBottom:16}},onExportExcel&&iconButton('Export panels Excel','excel',onExportExcel),onExportPDF&&iconButton('Export panels PDF','pdf',onExportPDF),isAdmin&&onAddOffcut&&iconButton('Add panel offcut','offcut',onAddOffcut)),
    h('div',{className:'ws-inventory'},
     h('div',{className:'ws-tabs',role:'group','aria-label':'Stock categories'},Object.entries(categories).map(([key,label])=>h('button',{type:'button',key,className:category===key?'is-active':'','aria-pressed':category===key,onClick:()=>setCategory(key)},label,h('span',null,key==='all'?allItems.length:allItems.filter(i=>i.category===key).length)))),
     h('div',{className:'ws-filters'},h('label',{className:'ws-search'},icon('search'),h('input',{'aria-label':'Search stock',value:search,placeholder:'Search by item, code, location or supplier…',onChange:e=>setSearch(e.target.value)})),h('select',{'aria-label':'Stock status',value:status,onChange:e=>setStatus(e.target.value)},[['all','All statuses'],['reorder','Needs restocking'],['reserved','Allocated to jobs'],['unassigned','Location needed']].map(([v,t])=>h('option',{value:v,key:v},t))),h('select',{'aria-label':'Sort stock',value:sort,onChange:e=>setSort(e.target.value)},[['name','Sort: item name'],['available','Sort: lowest available'],['location','Sort: location']].map(([v,t])=>h('option',{value:v,key:v},t)))),
     h('div',{className:'ws-list-caption'},h('span',null,h('strong',null,categories[category]),' · '+items.length+' '+(items.length===1?'item':'items')), (status!=='all'||search||category!=='all')&&button('Clear filters',resetFilters)),
     isAdmin&&h('div',{className:'ws-bulk-toolbar'},h('label',null,h('input',{type:'checkbox','aria-label':'Select all visible stock items',checked:items.length>0&&items.every(i=>selectedIds.includes(i.id)),disabled:busy||!!pending||!items.length,onChange:e=>setSelectedIds(ids=>e.target.checked?[...new Set([...ids,...items.map(i=>i.id)])]:ids.filter(id=>!items.some(i=>i.id===id)))}),'Select visible'),h('span',null,selectedStock.length+' selected'),button('Bulk edit',openBulk,busy||!!pending||!selectedStock.length||selectedStock.length>500),selectedIds.length>0&&button('Clear selection',()=>setSelectedIds([]),busy||!!pending)),
     h('div',{className:'ws-table'},h('table',null,h('thead',null,h('tr',null,['Stock item','Location','On hand','Reserved','Available','Reorder at','Status','Actions'].map(t=>h('th',{key:t},t)))),h('tbody',null,items.map(item=>{
      const [tone,label]=stockStatus(item);
      const name=item.name;
      const detail=item.legacy&&item.width?item.thickness+' mm · '+item.width+' × '+item.height+' mm':[item.dimensions,item.lengthMm?String(Number(item.lengthMm))+' mm long':'',item.colour].filter(Boolean).join(' · ')||item.details;
      return h('tr',{key:item.id},
       h('td',null,h('div',{className:'ws-product'},isAdmin&&h('input',{type:'checkbox',className:'ws-stock-select','aria-label':'Select '+item.name+' '+(item.sku||''),checked:selectedIds.includes(item.id),disabled:busy||!!pending,onChange:e=>toggleSelected(item.id,e.target.checked)}),item.legacy&&item.colorHex?h('span',{className:'ws-panel-swatch',role:'img','aria-label':(item.color||'Panel')+' '+item.colorHex,title:(item.color||'Panel')+' · '+item.colorHex,style:{backgroundColor:item.colorHex}}):item.image?h('button',{type:'button',className:'ws-thumbnail','aria-label':'View image for '+item.name,onClick:()=>setPreview(item)},h('img',{src:item.image,alt:item.name+' profile',loading:'lazy'})):h('span',{className:'ws-product-icon'},icon('box')),h('div',null,h('strong',null,name),detail&&h('small',{className:'ws-spec'},detail),h('div',{className:'ws-item-meta'},h('span',{className:'ws-sku'},item.sku||'No code'),h('span',null,categories[item.category]))))),
       h('td',null,item.location?h('span',{className:'ws-location'},icon('pin'),item.location):isAdmin?h('button',{type:'button',className:'ws-location-add',onClick:()=>open(item,'metadata')},'+ Add location'):h('span',{className:'ws-muted'},'Not assigned')),
       h('td',{className:'ws-number'},qty(item.qty),h('small',null,item.unit)),
       h('td',{className:'ws-number'},item.reserved>0?h('span',{className:'ws-reserved'},qty(item.reserved)):h('span',{className:'ws-muted'},'—')),
       h('td',{className:'ws-number ws-available '+tone},qty(item.available)),
       h('td',{className:'ws-number'},Number(item.reorderLevel)>0?qty(item.reorderLevel):h('span',{className:'ws-muted',title:'No minimum stock level set'},'—')),
       h('td',null,h('span',{className:'ws-badge '+tone},h('i',null),label)),
       h('td',null,h('select',{className:'ws-action-select','aria-label':'Stock action for '+item.name,value:'',onChange:e=>{const action=e.target.value;if(action==='panels')onPanels(item);else if(action==='history')setHistory(item.id);else if(action)open(item,action);}},h('option',{value:''},'Manage'),item.legacy?h(React.Fragment,null,h('option',{value:'panels'},'View stock details'),isAdmin&&h('option',{value:'metadata'},'Edit details')):h(React.Fragment,null,Object.entries(actions).filter(([a])=>!['category_save','bulk_metadata'].includes(a)&&allowed(a)).map(([a,t])=>h('option',{key:a,value:a},t)),isAdmin&&h('option',{value:'variant'},'Add colour / length variant'),h('option',{value:'history'},'View history')))));
     })))),
     !items.length&&h('div',{className:'ws-empty'},icon('box'),h('h3',null,allItems.length?'No matching stock':'Start your workshop inventory'),h('p',null,allItems.length?'Try a different search or clear your filters.':'Add your first item with an opening quantity and storage location.'),allItems.length?button('Clear filters',resetFilters):isAdmin&&button('Add stock item',()=>open(null,'create'))),
     h('div',{className:'ws-table-footer'},'Quantities are shown in each item’s stock unit.',h('span',null,'Available = on hand − reserved'))
    ),
    ),
    stockArea==='stock'&&h('details',{className:'ws-help'},h('summary',null,'How stock and allocations work'),h('p',null,'CNC scheduling reserves panel sheets automatically. Use Receive, Dispatch, Convert and Damage for sheets and sheet offcuts. Reserve other stock against a job here, then record usage when the material is used. Release unused allocations to make stock available again.')),
    history&&h('div',{className:'ws-history'},h('div',{className:'ws-heading'},h('h3',null,'Movement history'),button('Close',()=>setHistory(null))),h('p',null,'Current reservations: '+Object.entries(data.items.find(i=>i.id===history)?.reservations||{}).filter(([,q])=>q>0).map(([job,q])=>job+': '+q).join(', ')),data.movements.filter(m=>m.itemId===history).map(m=>h('p',{key:m.id},new Date(m.at).toLocaleString('en-AU')+' · '+m.action+' · '+m.quantity+' · '+m.user+(m.job?' · '+m.job:'')+(m.reason?' · '+m.reason:''))))
   ),
   countList&&h('div',{className:'ws-overlay'},h('div',{className:'ws-dialog ws-count-dialog',role:'dialog','aria-modal':true,'aria-label':'Stocktakes'},
    h('div',{className:'ws-count-header'},h('div',{className:'ws-heading'},h('h3',null,'Stocktakes'),button('Close',()=>setCountList(false))),h('p',null,'Choose a count to start or continue. Submitted quantities update stock and shared progress.'),isAdmin&&button('Create stocktake',()=>{setCountList(false);open(null,'stocktake_create');setForm(f=>({...f,name:'',categories:[]}));})),
    h('div',{className:'ws-count-body'},error&&h('div',{className:'ws-error',role:'alert'},error),!(data?.stocktakes||[]).length&&h('p',null,'No stocktakes yet. An administrator can create a named count and choose its categories.'),...(data?.stocktakes||[]).map(c=>h('div',{key:c.id,className:'ws-count-session'},h('div',null,h('strong',null,c.name),h('p',null,c.categories.map(k=>categories[k]||k).join(' · ')),h('small',null,Object.keys(c.counts).length+' of '+c.itemIds.length+' counted · '+(c.status==='completed'?'Completed':'Open'))),c.status==='open'&&button(Object.keys(c.counts).length?'Continue count':'Start count',()=>startCount(c),busy)))))),
   counting&&h('div',{className:'ws-overlay'},h('div',{className:'ws-dialog ws-count-dialog',role:'dialog','aria-modal':true,'aria-label':'Workshop stocktake'},
    h('div',{className:'ws-count-header'},h('div',{className:'ws-eyebrow'},'WORKSHOP / STOCKTAKE'),h('div',{className:'ws-count-title'},h('h3',null,review?'Review '+activeCount?.name:activeCount?.name||'Stocktake'),h('span',{className:'ws-count-saved'},'Draft saved on this device')),h('p',null,'Count physical stock, including reserved items. Leave uncounted items blank.'),h('div',{className:'ws-count-progress'},h('strong',null,countedTotal+' of '+countItems.length+' counted'),h('span',null,(countItems.length-countedTotal)+' remaining')),h('progress',{max:countItems.length||1,value:countedTotal,'aria-label':'Stocktake progress'})),
    h('div',{className:'ws-count-body'},
    h('div',{className:'ws-fields ws-count-filters'},!review&&h('label',{className:'ws-field'},'Location',h('select',{'aria-label':'Stocktake location',value:countLocation,onChange:e=>setCountLocation(e.target.value)},h('option',{value:''},'All locations'),[...new Set(countItems.map(i=>i.location||'Unassigned'))].sort().map(v=>h('option',{key:v,value:v},v)))),!review&&h('label',{className:'ws-field'},'Find item',h('input',{value:countSearch,onChange:e=>setCountSearch(e.target.value),placeholder:'Code, colour or profile'}))),
    h('div',{className:'ws-count-toolbar'},h('span',null,visibleCounts.length+' '+(visibleCounts.length===1?'item':'items')+' shown'),!review&&h('div',{className:'ws-count-toggle',role:'group','aria-label':'Count filter'},['all','uncounted'].map(v=>h('button',{type:'button',key:v,'aria-pressed':countFilter===v,onClick:()=>{setCountFilter(v);setCountActive(null);}},v==='all'?'All items':'Uncounted')))),
    h('div',{className:'ws-count-list'},visibleCounts.map(i=>{
     const count=countDraft.counts[i.id],changed=count&&count.quantity!==''&&count.expectedQty!==i.qty;
     return h('div',{className:'ws-count-row '+(hasCount(i)?'is-counted':''),key:i.id},i.image?h('button',{type:'button',className:'ws-count-image','aria-label':'Enlarge profile '+i.sku,onClick:()=>setPreview(i)},h('img',{src:i.image,alt:i.name+' profile'})):h('span',{className:'ws-count-image ws-count-placeholder'},icon('box')),h('div',{className:'ws-count-identity'},h('strong',null,i.name),h('div',{className:'ws-count-specs'},h('span',{className:'ws-sku'},i.sku),i.colour&&h('span',{className:'ws-count-colour'},i.colour),i.lengthMm&&h('span',null,String(Number(i.lengthMm))+' mm')),i.dimensions&&h('small',null,i.dimensions),h('small',null,(i.location||'Unassigned')+' · '+i.unit),review&&h('small',null,'Recorded: '+qty(i.qty)+' · Difference: '+qty(Number(count.quantity)-i.qty)),changed&&h('span',{className:'ws-error'},'Stock changed. Recount and enter the quantity again.')),h('label',{className:'ws-field'},hasCount(i)?'✓ Counted ('+i.unit+')':'Count ('+i.unit+')',h('input',{'data-count-input':true,onFocus:()=>setCountActive(i.id),onBlur:()=>setCountActive(null),onKeyDown:e=>{if(e.key==='Enter'){e.preventDefault();const inputs=[...e.currentTarget.closest('.ws-count-list').querySelectorAll('[data-count-input]')];const next=inputs[inputs.indexOf(e.currentTarget)+1];if(next){next.focus();next.select();}else e.currentTarget.blur();}},type:'number',inputMode:'decimal',min:0,step:'0.001','aria-label':'Count '+i.sku+' '+(i.colour||'')+' '+(i.lengthMm||''),value:count?.quantity??'',placeholder:'Not counted',disabled:busy||!!countDraft.request,onChange:e=>enterCount(i,e.target.value)})));
    })),!visibleCounts.length&&h('div',{className:'ws-count-empty'},h('strong',null,review?'No counts to review':countFilter==='uncounted'?'No uncounted items match':'No items match'),h('p',null,'Change the filters or return to all items.')),h('p',{className:'ws-count-tip'},'Enter moves to the next quantity. Submit your counts to share progress with the team.'),error&&h('div',{className:'ws-error',role:'alert'},error),countDraft.request&&h('p',null,'Save status is uncertain. Retry the same submission to avoid duplicate adjustments.')),
    h('div',{className:'ws-actions ws-count-footer'},button('Save & close',()=>{setCounting(false);setCountList(true);},busy),button(review?'Back to counting':'Review counts',()=>setReview(!review),busy),review&&h('button',{type:'button',className:'ws-primary',onClick:submitCounts,disabled:busy||(!countDraft.request&&(!countDraft.reference.trim()||!countItems.some(hasCount)||countItems.some(i=>countDraft.counts[i.id]?.quantity!==undefined&&countDraft.counts[i.id]?.quantity!==''&&countDraft.counts[i.id].expectedQty!==i.qty)))},busy?'Saving…':countDraft.request?'Retry submission':'Submit stocktake')))),
   form&&h('div',{className:'ws-overlay'},h('form',{className:'ws-dialog '+(['create','metadata'].includes(form.action)?'ws-create-dialog':''),onSubmit:save,role:'dialog','aria-modal':true,'aria-label':form.action==='create'?(form.variant?'Add stock variant':'Add stock item'):actions[form.action]},h('div',{className:'ws-form-heading'},h('span',{className:'ws-eyebrow'},form.action==='create'?'WORKSHOP INVENTORY':'STOCK DETAILS'),h('h3',null,form.action==='create'?(form.variant?'Add stock variant':'Add stock item'):actions[form.action]),form.action==='create'&&h('p',null,sharedProfile?'Shared profile: '+sharedProfile.sku+'. Choose a different colour or length and enter its stock quantity.':'Set up the item, add its profile and record your starting stock.')),selected&&h('div',{className:'ws-edit-identity'},h('strong',null,selected.name),h('span',{className:'ws-sku'},selected.sku||'No code'),h('span',null,categories[selected.category]+' · '+selected.unit)),
    form.action==='metadata'&&!selected?.legacy&&profileVariants(selected)>1&&h('p',{className:'ws-field-hint'},'Profile image and dimensions are shared by all '+profileVariants(selected)+' variants. Colour, length and stock settings apply only to this variant.'),
    form.action==='bulk_metadata'?h('div',null,h('p',null,'Update '+form.itemIds.length+' selected stock items. Only checked fields will change. Empty text clears that field.'),h('div',{className:'ws-bulk-fields'},bulkFields.map(([key,label,type])=>{
     const checked=Object.hasOwn(form.changes,key),unsupported=bulkHasPanels&&['category','colour','lengthMm','dimensions'].includes(key);
     return h('div',{className:'ws-bulk-field',key},h('label',null,h('input',{type:'checkbox',checked,disabled:busy||!!pending||unsupported,onChange:e=>setForm(f=>{const changes={...f.changes};if(e.target.checked)changes[key]=key==='category'?'extrusions':key==='reorderLevel'?0:'';else delete changes[key];return {...f,changes};})}),label),type==='select'?h('select',{'aria-label':label,value:form.changes[key]??'extrusions',disabled:!checked||busy||!!pending||unsupported,onChange:e=>bulkChange(key,e.target.value)},Object.entries(categories).filter(([k])=>!['all','panels'].includes(k)).map(([value,label])=>h('option',{value,key:value},label))):h('input',{'aria-label':label,type,value:form.changes[key]??'',min:type==='number'?0:undefined,step:type==='number'?'0.001':undefined,disabled:!checked||busy||!!pending||unsupported,onChange:e=>bulkChange(key,e.target.value)}));
    })),h('p',{className:'ws-field-hint'},bulkHasPanels?'Panel sheets and panel offcuts support name, location, supplier and reorder changes. Select workshop items separately to edit their other fields.':'To change a profile’s category or shared dimensions, select all its colour and length variants. Quantities are changed through receiving, usage and stocktake.')):form.action==='stocktake_create'?h('div',null,field('Count name','name'),h('h4',null,'Categories to count'),h('div',{className:'ws-count-categories'},Object.entries(categories).filter(([key])=>!['all','panels'].includes(key)).map(([key,label])=>h('label',{key},h('input',{type:'checkbox',checked:(form.categories||[]).includes(key),disabled:busy||!!pending,onChange:e=>change('categories',e.target.checked?[...(form.categories||[]),key]:(form.categories||[]).filter(k=>k!==key))}),label,h('small',null,' ('+allItems.filter(i=>!i.legacy&&i.category===key).length+' items)')))),h('p',{className:'ws-field-hint'},'Includes current workshop items in these categories. Panel sheets and panel offcuts are excluded. Workers can submit part of the count and continue later.')):form.action==='category_save'?h('div',null,h('div',{className:'ws-fields'},field('Category to edit','categoryId','text',[['','Add new category'],...Object.entries(categories).filter(([key])=>key!=='all')]),field('Category name','name')),h('p',{className:'ws-field-hint'},'Renaming a category keeps its existing items and stock history. New categories become available when adding workshop stock. Panel sheets and offcuts retain their existing stock workflows.')):form.action==='create'?h('div',{className:'ws-create-content'},
     h('div',{className:'ws-create-top'},h('section',{className:'ws-form-section'},h('h4',null,'01',h('span',null,'Item details')),h('div',{className:'ws-fields'},field('Category','category','text',Object.entries(categories).filter(([k])=>!['all','panels'].includes(k))),field('Stock code','sku'),field(form.category==='extrusions'?'Profile name':'Item name','name'),field('Supplier','supplier'),field('Length (mm)','lengthMm','number'),field('Dimensions / profile size','dimensions'),field('Colour / finish','colour'),field('Additional notes','details'))),h('section',{className:'ws-form-section ws-profile-section'},h('h4',null,'02',h('span',null,'Profile image')),imageEditor())),
     h('section',{className:'ws-form-section ws-stock-section'},h('h4',null,'03',h('span',null,'Stock & storage')),h('div',{className:'ws-fields'},field('Stock unit','unit','text',['lengths','each','boxes','packs','rolls','tubes','litres','metres','kg'].map(v=>[v,v.charAt(0).toUpperCase()+v.slice(1)])),field('Opening quantity ('+form.unit+')','qty','number'),field('Reorder level ('+form.unit+')','reorderLevel','number'),field('Rack / shelf / bin','location'),['boxes','packs'].includes(form.unit)&&field('Units per pack (reference only)','packSize','number')),h('p',{className:'ws-field-hint'},'Opening quantity is what you have in the workshop now. Reorder level flags when available stock runs low.'))):
    form.action==='metadata'?h('div',{className:'ws-create-content'},h('div',{className:'ws-create-top'},h('section',{className:'ws-form-section'},h('h4',null,'01',h('span',null,'Specifications')),h('div',{className:'ws-fields'},h('div',{className:'ws-full-field'},field('Stock item name','name')),!selected?.legacy&&field('Length (mm)','lengthMm','number'),!selected?.legacy&&field('Dimensions / profile size','dimensions'),!selected?.legacy&&field('Colour / finish','colour'),field('Supplier','supplier'),!selected?.legacy&&h('div',{className:'ws-full-field'},field('Additional notes','details')),selected?.legacy&&selected.category==='offcuts'&&h('div',{className:'ws-full-field'},field('Catalogue material','catalogId','text',[['','Keep current material'],...(data.catalog||[]).map(c=>[c.id,[c.color,c.material,c.thickness+' mm'].join(' · ')])]),h('p',{className:'ws-field-hint'},'Choose the correct catalogue entry to replace the old typed colour, material and thickness. Size and quantity stay the same.')),selected?.legacy&&selected.category!=='offcuts'&&h('p',{className:'ws-field-hint'},'Panel dimensions and material are managed in panel stock.'))),h('section',{className:'ws-form-section ws-profile-section'},h('h4',null,'02',h('span',null,'Profile image')),imageEditor())),h('section',{className:'ws-form-section ws-stock-section'},h('h4',null,'03',h('span',null,'Storage & reorder level')),h('div',{className:'ws-fields ws-edit-storage'},field('Rack / shelf / bin','location'),field('Reorder level ('+selected?.unit+')','reorderLevel','number'),h('div',{className:'ws-readonly-stock'},h('span',null,'Current stock'),h('strong',null,qty(selected?.qty)+' '+selected?.unit),h('small',null,qty(selected?.available)+' available · '+qty(selected?.reserved)+' reserved'))))):
    h('div',{className:'ws-fields'},field(form.action==='stocktake'?'Actual counted quantity':'Quantity','quantity','number'),['use','return','reserve','release'].includes(form.action)&&field('Job reference','job'),field(['damage','stocktake'].includes(form.action)?'Reason (required)':'Delivery reference / notes','reason')),
    selected?.reservations&&Object.values(selected.reservations).some(q=>q>0)&&h('p',{className:'ws-field-hint'},'Reserved for jobs: '+Object.entries(selected.reservations).filter(([,q])=>q>0).map(([j,q])=>j+': '+q).join(', ')),
    error&&h('div',{className:'ws-error',role:'alert'},error),pending&&!busy&&h('p',null,'Save status is uncertain. Retry this unchanged request before starting another movement.'),
    h('div',{className:'ws-actions'},button('Cancel',()=>setForm(null),busy||imageBusy||!!pending),h('button',{type:'submit',disabled:busy||imageBusy||(form.action==='bulk_metadata'&&!Object.keys(form.changes).length)},imageBusy?'Preparing image…':busy?'Saving…':pending?'Retry save':form.action==='create'?'Create stock item':form.action==='bulk_metadata'?'Apply to '+form.itemIds.length+' items':'Save')))),
   poOpen&&h(PurchaseOrderReceiving,{workerUrl,isAdmin,onClose:()=>{setPoOpen(false);load();},onReceived:load}),
   preview&&h('div',{className:'ws-overlay',onClick:e=>{if(e.target===e.currentTarget)setPreview(null);}},h('div',{className:'ws-dialog ws-image-viewer',role:'dialog','aria-modal':true,'aria-label':'Stock image'},h('div',{className:'ws-heading'},h('div',null,h('h3',null,preview.name),h('p',null,preview.sku)),h('button',{type:'button',autoFocus:true,onClick:()=>setPreview(null),'aria-label':'Close image'},'Close')),h('div',{className:'ws-preview-tools'},h('button',{type:'button','aria-pressed':enhanceOutline,onClick:()=>setEnhanceOutline(v=>!v)},enhanceOutline?'Original image':'Enhance outline'),h('span',null,'Use Enhance outline for pale profile drawings.')),h('img',{className:enhanceOutline?'ws-outline-enhanced':'',src:preview.image,alt:preview.name+' profile'})))
  );
 };
};

/* Purchase orders share stock identities with SOH and the existing Receive screen. */
/* Import matching only suggests existing stock; the admin reviews every line. */
window.matchPurchaseOrderLine=function(line,items){
 const normal=v=>String(v||'').trim().toLowerCase().replace(/\s+/g,' ');
 const sku=normal(line.sku),words=normal([line.description,line.colour,line.dimensions].join(' ')).split(/[^a-z0-9]+/).filter(w=>w.length>1);
 const exact=sku?items.filter(i=>normal(i.sku)===sku):[];
 const matches=exact.filter(i=>(!line.colour||normal(i.colour||i.color)===normal(line.colour))&&(!line.lengthMm||Number(i.lengthMm)===Number(line.lengthMm))&&(!line.dimensions||normal(i.dimensions)===normal(line.dimensions)));
 const scored=items.map(i=>{const hay=normal([i.sku,i.name,i.colour||i.color,i.dimensions,i.lengthMm].join(' '));return {item:i,score:(sku&&normal(i.sku)===sku?100:0)+words.filter(w=>hay.includes(w)).length};}).filter(v=>v.score>0).sort((a,b)=>b.score-a.score);
 return {itemId:matches.length===1?matches[0].id:'',candidates:scored.slice(0,8).map(v=>v.item.id)};
};
window.createPurchaseOrderReceiving=function(React){
 const h=React.createElement,{useState,useEffect}=React;
 const statusLabels={draft:'Draft',open:'Awaiting delivery',partial:'Part received',received:'Received',closed_short:'Closed short',cancelled:'Cancelled'};
 const num=value=>Number(value||0).toLocaleString('en-AU',{maximumFractionDigits:3});
 const remaining=line=>Math.round((line.ordered-line.received)*1000)/1000;
 const identity=item=>[item.sku,item.name,item.colour||item.color,item.dimensions,item.lengthMm?item.lengthMm+' mm':null,item.width?item.width+' × '+item.height+' mm':null].filter(Boolean).join(' · ');
 return function PurchaseOrderReceiving({workerUrl,isAdmin,onClose,onReceived,launcher=false}){
  const [visible,setVisible]=useState(!launcher),[data,setData]=useState(null),[selected,setSelected]=useState(null),[editor,setEditor]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[filter,setFilter]=useState('outstanding'),[search,setSearch]=useState(''),[itemSearch,setItemSearch]=useState(''),[itemId,setItemId]=useState(''),[itemQuantity,setItemQuantity]=useState(''),[delivery,setDelivery]=useState({quantities:{},reference:'',notes:''}),[review,setReview]=useState(false),[cancelReason,setCancelReason]=useState(null),[fileRetry,setFileRetry]=useState(null);
  const [issueForm,setIssueForm]=useState(null),[closeReason,setCloseReason]=useState(null),[resolution,setResolution]=useState(null);
  const [stagedFile,setStagedFile]=useState(null),[importRows,setImportRows]=useState(null),[importWarnings,setImportWarnings]=useState([]),[importReviewed,setImportReviewed]=useState(false);
  const [newStock,setNewStock]=useState(null);
  const [receivingFilter,setReceivingFilter]=useState('outstanding'),[receivingSearch,setReceivingSearch]=useState('');
  const issueLabels={damaged:'Damaged',missing:'Missing',incorrect:'Incorrect item'};
  const pendingKey='panelstock:po-pending:'+PanelStock.username;
  const [pending,setPending]=useState(()=>{try{return JSON.parse(localStorage.getItem(pendingKey)||'null');}catch{return null;}});
  const order=data?.orders.find(o=>o.id===selected),locked=busy||!!pending||!!fileRetry||!!newStock;
  async function request(path,body){const response=await PanelStock.apiFetch(workerUrl+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const result=await response.json();if(!response.ok){const e=Error(result.error||'Purchase orders could not be loaded');e.status=response.status;throw e;}return result;}
  async function load(){try{const result=await request('/purchase-orders');setData(result);setError('');return result;}catch(e){setError(e.message);return null;}}
  useEffect(()=>{if(visible||launcher)load();},[visible,launcher]);
  function openOrder(value){setIssueForm(null);setCloseReason(null);setResolution(null);setSelected(value.id);setEditor(value.status==='draft'?{reference:value.reference,supplier:value.supplier,notes:value.notes,lines:value.lines.map(l=>({itemId:l.itemId,ordered:l.ordered}))}:null);setDelivery({quantities:{},reference:'',notes:''});setItemSearch('');setItemId('');setItemQuantity('');setReview(false);setError('');setNotice('');setCancelReason(null);}
  function editOrder(){setEditor({reference:order.reference,supplier:order.supplier,notes:order.notes,lines:order.lines.map(l=>({itemId:l.itemId,ordered:l.ordered}))});setReview(false);setCancelReason(null);setError('');}
  function newOrder(){setStagedFile(null);setImportRows(null);setImportWarnings([]);setImportReviewed(false);setSelected(null);setEditor({reference:'',supplier:'',notes:'',lines:[]});setError('');setNotice('');}
  function duplicateOrder(){setStagedFile(null);setImportRows(null);setImportWarnings([]);setSelected(null);setEditor({reference:'',supplier:order.supplier,notes:order.notes||'',lines:order.lines.map(l=>({itemId:l.itemId,ordered:l.ordered}))});setNotice('Copied the supplier and ordered items. Enter a new PO number and attach the new document. Receipts and delivery issues are not copied.');setError('');setReview(false);}
  async function readDocument(event){
   const file=event.target.files?.[0];event.target.value='';if(!file)return;
   if(!/\.(pdf|png|jpe?g|xlsx)$/i.test(file.name)||file.size>5*1024*1024||!file.size){setError('Choose a PDF, JPG, PNG or Excel file up to 5 MB.');return;}
   setBusy(true);setError('');setNotice('Reading the PO. This can take up to a minute.');setImportReviewed(false);
   try{
    const encoded=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('Could not read this file'));reader.readAsDataURL(file);});
    const attachment={id:crypto.randomUUID(),name:file.name,data:encoded};setStagedFile(attachment);setImportRows(null);setImportWarnings([]);setEditor({reference:'',supplier:'',notes:'',lines:[]});
    const result=await request('/purchase-orders/analyse',{name:file.name,data:encoded});
    setEditor({reference:result.reference||'',supplier:result.supplier||'',notes:result.notes||'',lines:[]});
    setImportWarnings(result.warnings||[]);
    setImportRows(result.lines.map((line,index)=>({...line,key:index,itemId:window.matchPurchaseOrderLine(line,data.items).itemId,search:'',ordered:line.quantity??''})));
    setNotice(result.lines.length?'Document read. Review the PO details, stock matches, units and quantities below.':'No stock lines were read. Add the items manually or choose another document.');
    if(!result.lines.length)setImportRows(null);
   }catch(e){setError(e.message+' Your document is selected; you can enter its details manually.');setNotice('');}finally{setBusy(false);}
  }
  function startStock(row=null){
   const unitText=String(row?.unit||'').toLowerCase(),units={length:'lengths',lengths:'lengths',ea:'each',each:'each',box:'boxes',boxes:'boxes',pack:'packs',packs:'packs',roll:'rolls',rolls:'rolls',tube:'tubes',tubes:'tubes',litre:'litres',litres:'litres',metre:'metres',metres:'metres',kg:'kg',sheet:'sheets',sheets:'sheets'};
   const unit=units[unitText]||'each',category=unit==='sheets'?'panels':unit==='lengths'?'extrusions':unit==='boxes'?'fixings':'consumables';
   const profile=data.items.find(i=>!i.legacy&&String(i.sku).trim().toLowerCase()===String(row?.sku||itemSearch||'').trim().toLowerCase());
   setNewStock({sourceRowKey:row?.key??null,sku:row?.sku||itemSearch||'',name:row?.description||'',category,unit,colour:row?.colour||'',lengthMm:row?.lengthMm||'',dimensions:row?.dimensions||'',supplier:editor?.supplier||'',material:'',thickness:'',width:'',height:'',...(profile?{category:profile.category,unit:profile.unit,name:profile.name,dimensions:profile.dimensions||''}:{})});setError('');
  }
  const stockLabels={panels:'Panels',extrusions:'Extrusions',fixings:'Fixings',consumables:'Consumables',offcuts:'Offcuts',...data?.categories};
  const existingProfile=newStock&&data?.items.find(i=>!i.legacy&&String(i.sku).trim().toLowerCase()===newStock.sku.trim().toLowerCase());
  function stockChange(key,value){setNewStock(current=>{const next={...current,[key]:value};if(key==='category')next.unit=value==='panels'?'sheets':value==='extrusions'?'lengths':'each';if(key==='sku'){const profile=data.items.find(i=>!i.legacy&&String(i.sku).trim().toLowerCase()===value.trim().toLowerCase());if(profile)Object.assign(next,{category:profile.category,unit:profile.unit,name:profile.name,dimensions:profile.dimensions||''});}return next;});}
  const stockField=(label,key,type='text')=>h('label',{className:'ws-field'},label,h('input',{type,value:newStock[key],autoFocus:key==='sku',disabled:busy||!!pending||(!!existingProfile&&['name','dimensions'].includes(key)),maxLength:type==='text'?160:undefined,min:type==='number'?0.001:undefined,step:type==='number'?0.001:undefined,onChange:e=>stockChange(key,e.target.value)}));
  function useImport(){
   const totals=new Map();for(const row of importRows||[])totals.set(row.itemId,Math.round(((totals.get(row.itemId)||0)+Number(row.ordered))*1000)/1000);
   setEditor({...editor,lines:[...totals].map(([itemId,ordered])=>({itemId,ordered}))});setImportRows(null);setNotice('Reviewed items added. Save this draft or make it available for receiving.');
  }
  function close(){if(locked)return;if(launcher)setVisible(false);else onClose?.();}
  async function mutate(input){
   if(fileRetry||busy)return;
   const payload=pending||{...input,orderId:input.orderId||selected||crypto.randomUUID(),expectedVersion:order?.version||0,restoreEpoch:data.restoreEpoch,mutationId:crypto.randomUUID()};
   setBusy(true);setError('');setNotice('');
   try{
    localStorage.setItem(pendingKey,JSON.stringify(payload));setPending(payload);
    let result=await request('/purchase-orders',payload);localStorage.removeItem(pendingKey);setPending(null);setData(result);
    if(payload.action==='create_item'){
     if(payload.sourceRowKey!==null&&payload.sourceRowKey!==undefined){setImportRows(rows=>rows?.map(row=>row.key===payload.sourceRowKey?{...row,itemId:result.itemId,search:''}:row)||null);setImportReviewed(false);}else{setItemId(result.itemId);setItemSearch('');}
     setNewStock(null);setNotice('Stock item created at zero on hand and selected for this PO. Save the PO, then receive its delivery to add stock.');onReceived?.();return;
    }
    if(payload.action==='save'&&stagedFile){
     const attachment={...stagedFile,orderId:result.orderId,restoreEpoch:result.restoreEpoch};setFileRetry(attachment);
     const saved=result.orders.find(o=>o.id===result.orderId);if(saved)openOrder(saved);
     try{result=await request('/purchase-orders/'+result.orderId+'/files',attachment);setData(result);setFileRetry(null);setStagedFile(null);}catch(e){setError('Draft saved, but its document upload needs retrying. '+e.message);return;}
    }
    if(payload.action==='save'&&payload.publishAfterSave){
     const saved=result.orders.find(o=>o.id===result.orderId);if(saved)openOrder(saved);
     const release={action:'publish',orderId:saved.id,expectedVersion:saved.version,restoreEpoch:result.restoreEpoch,mutationId:crypto.randomUUID()};
     localStorage.setItem(pendingKey,JSON.stringify(release));setPending(release);
     result=await request('/purchase-orders',release);localStorage.removeItem(pendingKey);setPending(null);setData(result);
    }
    const updated=result.orders.find(o=>o.id===result.orderId);if(updated)openOrder(updated);if(payload.action==='save')setFilter(updated?.status==='draft'?'draft':'all');if(payload.action==='publish'||payload.publishAfterSave)setFilter('outstanding');
    setNotice(payload.action==='receive'?'Delivery received. Stock and outstanding quantities updated.':(payload.action==='publish'||payload.publishAfterSave)?'PO is now available for workers to receive.':payload.action==='report_issue'?'Delivery issue recorded. Add photos below if needed. Stock has not changed.':payload.action==='resolve_issue'?'Delivery issue resolved. Stock has not changed.':payload.action==='close_short'?'PO closed short. Received stock is preserved; the balance is no longer on order.':payload.action==='cancel'?'PO cancelled. Previous receipts are retained.':updated?.status==='draft'?'Draft saved. Upload the PO and check its items before making it available.':'Purchase order updated. Received stock and delivery history are preserved.');
    onReceived?.();
   }catch(e){
    if(e.status&&e.status<500){localStorage.removeItem(pendingKey);setPending(null);if(e.status===409){setReview(false);await load();}}
    setError(e.message+(e.status===409?' Review the current outstanding quantities before submitting again.':''));
   }finally{setBusy(false);}
  }
  async function upload(event,issueId=null){
   const file=event?.target?.files?.[0];if(event)event.target.value='';if(!file&&!fileRetry)return;
   if(file&&(!/\.(pdf|png|jpe?g|xlsx)$/i.test(file.name)||file.size>5*1024*1024)){setError('Choose a PDF, PNG, JPG or Excel file up to 5 MB.');return;}
   setBusy(true);setError('');let payload=fileRetry;
   try{
    if(!payload){const encoded=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('Could not read the PO file'));reader.readAsDataURL(file);});payload={id:crypto.randomUUID(),name:file.name,data:encoded,restoreEpoch:data.restoreEpoch,...(issueId?{issueId}:{})};setFileRetry(payload);}
    const result=await request('/purchase-orders/'+(payload.orderId||selected)+'/files',payload);setData(result);setFileRetry(null);if(payload.orderId)setStagedFile(null);setNotice(payload.issueId?'Delivery issue photo saved.':'PO document uploaded. Save the item list, then make it available for receiving.');
   }catch(e){if(e.status&&e.status<500)setFileRetry(null);setError(e.message);}finally{setBusy(false);}
  }
  async function download(file){
   setBusy(true);setError('');
   try{const result=await request('/purchase-orders/'+selected+'/files/'+file.id),bytes=Uint8Array.from(atob(result.file.data),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:file.type})),link=document.createElement('a');link.href=url;link.download=file.name;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(e){setError(e.message);}finally{setBusy(false);}
  }
  const button=(label,onClick,disabled=locked,primary=false)=>h('button',{type:'button',onClick,disabled,className:primary?'ws-primary':undefined},label);
  const editField=(label,key)=>h('label',{className:'ws-field'},label,key==='notes'&&h('span',{className:'ws-po-optional'},'Optional'),h(key==='notes'?'textarea':'input',{value:editor[key],disabled:locked,rows:key==='notes'?2:undefined,placeholder:{reference:'e.g. PO-2026-104',supplier:'Supplier name',notes:'Delivery instructions or a note for the receiving team'}[key],maxLength:key==='reference'?100:key==='notes'?1000:160,onChange:e=>setEditor({...editor,[key]:e.target.value})}));
  const selectedLines=editor?.lines||[],lookup=id=>data?.items.find(i=>i.id===id);
  const addingItem=lookup(itemId),addingQuantity=Number(itemQuantity);
  const validAddingQuantity=itemQuantity!==''&&Number.isFinite(addingQuantity)&&addingQuantity>0&&addingQuantity<=1e9&&(addingItem?.legacy?Number.isInteger(addingQuantity):Math.abs(addingQuantity*1000-Math.round(addingQuantity*1000))<0.0001);
  function addLine(){if(locked||!itemId||!validAddingQuantity||selectedLines.length>=200)return;setEditor({...editor,lines:[...editor.lines,{itemId,ordered:addingQuantity}]});setItemId('');setItemQuantity('');}
  const candidates=(data?.items||[]).filter(i=>!selectedLines.some(l=>l.itemId===i.id)&&identity(i).toLowerCase().includes(itemSearch.toLowerCase())).slice(0,150);
  const invalidImport=!!importRows&&(!importRows.length||!importReviewed||importRows.some(row=>{const item=lookup(row.itemId),n=Number(row.ordered);return !item||row.ordered===''||!Number.isFinite(n)||n<=0||n>1e9||(item.legacy?!Number.isInteger(n):Math.abs(n*1000-Math.round(n*1000))>0.0001);}));
  const dirty=!!order&&editor&&JSON.stringify({reference:order.reference,supplier:order.supplier,notes:order.notes,lines:order.lines.map(l=>({itemId:l.itemId,ordered:l.ordered}))})!==JSON.stringify(editor);
  const receiptLines=order?.lines.filter(l=>Number(delivery.quantities[l.itemId])>0)||[];
  const invalidReceipt=!receiptLines.length||Object.entries(delivery.quantities).some(([id,value])=>value!==''&&(!Number.isFinite(Number(value))||Number(value)<0||Number(value)>(order?.lines.find(l=>l.itemId===id)?remaining(order.lines.find(l=>l.itemId===id)):0)));
  const orders=(data?.orders||[]).filter(o=>(filter==='all'||filter==='issues'&&(o.issues||[]).some(i=>i.status==='open')||filter==='outstanding'&&['open','partial'].includes(o.status)||filter===o.status)&&[o.reference,o.supplier].join(' ').toLowerCase().includes(search.toLowerCase()));
  const receivingTabs=[['outstanding','To receive'],['partial','Part received'],['completed','Completed']];
  const inReceivingTab=(o,key)=>key==='outstanding'?['open','partial'].includes(o.status):key==='completed'?['received','closed_short'].includes(o.status):o.status===key;
  const receivingOrders=(data?.orders||[]).filter(o=>inReceivingTab(o,receivingFilter)&&[o.reference,o.supplier,...o.lines.map(l=>l.name+' '+l.sku)].join(' ').toLowerCase().includes(receivingSearch.trim().toLowerCase()));
  const openReceiving=o=>{openOrder(o);setVisible(true);};
  const statusBadge=value=>h('span',{className:'ws-po-status '+value},statusLabels[value]);
  return h('section',{className:'ws ws-po'+(launcher?' ws-po-launcher-section':'')},launcher&&h('div',{className:'ws-receiving-home'},
   h('header',{className:'ws-receiving-heading'},h('div',null,h('div',{className:'ws-eyebrow'},'INVENTORY / RECEIVING'),h('h2',null,'Receive stock'),h('p',null,'Choose the purchase order for this delivery. Only accepted quantities are added to stock.')),h('div',{className:'ws-receiving-actions'},button('Refresh',load,locked),button(isAdmin?'Manage POs':'All purchase orders',()=>{setSelected(null);setEditor(null);setFilter('all');setVisible(true);},locked||!data),isAdmin&&button('New purchase order',()=>{newOrder();setVisible(true);},locked||!data,true))),
   h('div',{className:'ws-receiving-tabs',role:'group','aria-label':'Receiving views'},receivingTabs.map(([key,label])=>h('button',{key,type:'button','aria-pressed':receivingFilter===key,disabled:locked,onClick:()=>setReceivingFilter(key)},h('span',null,label),h('strong',null,data?(data.orders||[]).filter(o=>inReceivingTab(o,key)).length:'—')))),
   h('div',{className:'ws-receiving-toolbar'},h('label',{className:'ws-field'},'Find a delivery',h('input',{type:'search',value:receivingSearch,placeholder:'Search PO number, supplier or item',disabled:locked,onChange:e=>setReceivingSearch(e.target.value)})),h('span',null,receivingFilter==='partial'?'Orders with deliveries still outstanding':receivingFilter==='completed'?'Fully received and closed-short orders':'Open and partially received purchase orders')),
   !visible&&error&&h('div',{className:'ws-error',role:'alert'},error),!visible&&notice&&h('div',{className:'ws-notice',role:'status'},notice),
   !data?h('div',{className:'ws-receiving-empty',role:'status'},h('strong',null,error?'Purchase orders could not be loaded':'Loading purchase orders…'),h('p',null,error?'Use Refresh to try again.':'Checking deliveries ready to receive.')):!receivingOrders.length?h('div',{className:'ws-receiving-empty'},h('span',{className:'ws-receiving-empty-icon','aria-hidden':true},'✓'),h('h3',null,receivingSearch?'No matching purchase orders':receivingFilter==='completed'?'No completed orders yet':'No deliveries waiting here'),h('p',null,receivingSearch?'Try a PO number, supplier or stock item.':isAdmin?'Create or publish a PO to make it available for receiving.':'Your admin will make purchase orders available here.')):
   h('div',{className:'ws-receiving-list'},receivingOrders.map(o=>{const outstanding=o.lines.filter(l=>remaining(l)>0),complete=o.lines.filter(l=>remaining(l)===0).length,receivable=['open','partial'].includes(o.status),issues=(o.issues||[]).filter(i=>i.status==='open').length;
    return h('article',{className:'ws-receiving-card',key:o.id},h('div',{className:'ws-receiving-card-top'},h('div',null,h('span',{className:'ws-eyebrow'},'PURCHASE ORDER'),h('h3',null,o.reference),h('p',null,o.supplier)),statusBadge(o.status)),
     h('div',{className:'ws-receiving-progress'},h('span',null,complete+' of '+o.lines.length+' lines fully received'),h('div',{role:'progressbar','aria-label':o.reference+' item lines received','aria-valuenow':complete,'aria-valuemin':0,'aria-valuemax':Math.max(1,o.lines.length)},h('span',{style:{width:(o.lines.length?Math.round(100*complete/o.lines.length):0)+'%'}}))),
     h('div',{className:'ws-receiving-items'},(receivable?outstanding:o.lines).slice(0,2).map(l=>h('div',{key:l.itemId},h('span',null,l.name),h('strong',null,num(receivable?remaining(l):l.received)+' '+l.unit))),((receivable?outstanding:o.lines).length>2)&&h('small',null,'+'+((receivable?outstanding:o.lines).length-2)+' more items')),
     h('div',{className:'ws-receiving-card-bottom'},h('div',null,h('strong',null,receivable?outstanding.length+' '+(outstanding.length===1?'item':'items')+' outstanding':o.status==='closed_short'?'Unreceived balance closed':'Delivery complete'),issues>0&&h('span',{className:'ws-receiving-issue'},issues+' open delivery '+(issues===1?'issue':'issues')),o.receipts.length>0&&h('small',null,o.receipts.length+' '+(o.receipts.length===1?'delivery recorded':'deliveries recorded'))),button(receivable?'Receive delivery':'View order',()=>openReceiving(o),locked,receivable)));
   }))
  ),visible&&h('div',{className:'ws-overlay'},h('div',{className:'ws-dialog ws-count-dialog ws-po-dialog'+(editor?' ws-po-editing':''),role:'dialog','aria-modal':true,'aria-label':'Purchase order receiving'},
   h('div',{className:'ws-count-header'},h('div',{className:'ws-heading'},h('div',null,h('div',{className:'ws-eyebrow'},'INVENTORY / RECEIVING'),h('h3',null,order?'PO '+order.reference:editor?'New purchase order':'Purchase orders'),order&&h('p',null,order.supplier)),button('Close',close,locked)),order&&statusBadge(order.status),!order&&h('p',null,editor?'Upload your PO, review the details and stock matches, then save or make it available.':'Select a purchase order to record a delivery.')),
   h('div',{className:'ws-count-body'},newStock&&h('div',{className:'ws-po-stock-overlay'},h('div',{className:'ws-dialog ws-po-stock-dialog',role:'dialog','aria-modal':true,'aria-label':'Create stock item from PO'},h('div',{className:'ws-heading'},h('div',null,h('div',{className:'ws-eyebrow'},'PURCHASE ORDER / NEW STOCK'),h('h3',null,'Create stock item')),button('Close',()=>setNewStock(null),busy||!!pending)),h('p',null,'Creates a stock record at zero on hand. The item remains in SOH even if this PO is not saved.'),error&&h('div',{className:'ws-error',role:'alert'},error),pending?.action==='create_item'&&h('div',{className:'ws-po-warning'},'The stock save needs confirmation. Retry to safely select the same item.',button('Retry stock save',()=>mutate(pending),busy)),
      h('div',{className:'ws-fields'},stockField('Stock code','sku'),stockField('Item name','name'),h('label',{className:'ws-field'},'Category',h('select',{value:newStock.category,disabled:busy||!!pending||!!existingProfile,onChange:e=>stockChange('category',e.target.value)},Object.entries(stockLabels).map(([value,label])=>h('option',{key:value,value},label)))),h('label',{className:'ws-field'},'Stock unit',h('select',{value:newStock.unit,disabled:busy||!!pending||!!existingProfile||newStock.category==='panels',onChange:e=>stockChange('unit',e.target.value)},(newStock.category==='panels'?['sheets']:['lengths','each','boxes','packs','rolls','tubes','litres','metres','kg']).map(value=>h('option',{key:value,value},value)))),stockField('Colour','colour'),newStock.category==='panels'?h(React.Fragment,null,stockField('Material','material'),stockField('Thickness (mm)','thickness','number'),stockField('Sheet width (mm)','width','number'),stockField('Sheet height (mm)','height','number')):h(React.Fragment,null,stockField('Length (mm, optional)','lengthMm','number'),stockField('Dimensions / profile','dimensions')),stockField('Supplier','supplier')),
      existingProfile&&h('p',{className:'ws-notice'},'Existing stock code: shared name, category, unit and profile are retained. Set the new colour or length.'),h('div',{className:'ws-po-stock-zero'},h('span',null,'Opening stock'),h('strong',null,'0'),h('span',null,'Delivery quantities are added when received.')),
      h('div',{className:'ws-actions'},button('Cancel',()=>setNewStock(null),busy||!!pending),button('Create & select item',()=>{const {sourceRowKey,...item}=newStock;return mutate({action:'create_item',sourceRowKey,item:{...item,qty:0}});},busy||!!pending||!newStock.sku.trim()||!newStock.name.trim()||(newStock.category==='panels'&&(!newStock.colour.trim()||!newStock.material.trim()||!['thickness','width','height'].every(k=>Number(newStock[k])>0))),true))
     )),error&&h('div',{className:'ws-error',role:'alert'},error),notice&&h('div',{className:'ws-notice',role:'status'},notice),pending&&h('div',{className:'ws-po-warning'},'A save needs confirmation. Retry the same request to avoid receiving stock twice.',button('Retry save',()=>mutate(pending),busy)),fileRetry&&h('div',{className:'ws-po-warning'},'The file upload needs confirmation.',button('Retry upload',()=>upload(),busy)),
    !data?h('p',null,'Loading purchase orders…'):!selected&&!editor?h(React.Fragment,null,
     h('div',{className:'ws-po-filters'},h('label',{className:'ws-field'},'Find PO',h('input',{value:search,placeholder:'PO number or supplier',onChange:e=>setSearch(e.target.value)})),h('label',{className:'ws-field'},'Status',h('select',{value:filter,onChange:e=>setFilter(e.target.value)},[['outstanding','Awaiting delivery'],['issues','Delivery issues'],...(isAdmin?[['draft','Drafts']]:[]),['received','Received'],['closed_short','Closed short'],['cancelled','Cancelled'],['all','All POs']].map(([value,label])=>h('option',{key:value,value},label))))),
     !orders.length&&h('div',{className:'ws-count-empty'},h('strong',null,'No purchase orders in this view'),h('p',null,isAdmin?'Create a PO or choose another status.':'An admin will make purchase orders available here.')),
     orders.map(o=>h('button',{key:o.id,type:'button',className:'ws-po-card',disabled:locked,onClick:()=>openOrder(o)},h('div',null,h('strong',null,o.reference),h('p',null,o.supplier),h('small',null,o.lines.length+' items · '+o.lines.filter(l=>l.received<l.ordered).length+' outstanding')),statusBadge(o.status)))
    ):h(React.Fragment,null,
     editor&&!order&&h('section',{className:'ws-po-import-start ws-po-section'},h('div',{className:'ws-po-section-heading'},h('h4',null,'Start with your PO'),h('span',null,'1. Upload · 2. Review · 3. Save')),h('p',null,'Upload a supplier document to fill the details and suggest stock matches, or enter the order manually below.'),h('label',{className:'ws-po-import-upload'},h('strong',null,stagedFile?'Replace document':'Upload purchase order'),h('span',null,'PDF, Excel (.xlsx), JPG or PNG · up to 5 MB'),h('input',{type:'file',accept:'.pdf,.xlsx,.jpg,.jpeg,.png',disabled:locked,onChange:readDocument})),stagedFile&&h('p',{className:'ws-notice'},'Selected: '+stagedFile.name+' — attached when you save.'),importWarnings.length>0&&h('div',{className:'ws-po-warning'},h('strong',null,'Check the document'),importWarnings.map((w,i)=>h('p',{key:i},w)))),
     editor&&h('section',{className:'ws-po-editor ws-po-section'},h('div',{className:'ws-po-section-heading'},h('h4',null,'Order details'),h('span',null,'PO number and supplier are required')),h('div',{className:'ws-fields'},editField('PO number','reference'),editField('Supplier','supplier'),editField('Notes','notes'))),
     order&&h('section',{className:'ws-po-files'},h('h4',null,'PO documents'),order.attachments.filter(f=>!f.issueId).map(f=>button(f.name,()=>download(f),locked)),!order.attachments.some(f=>!f.issueId)&&h('p',null,'Upload the original PO before making it available to workers.'),isAdmin&&!!editor&&h('label',{className:'ws-field'},'Upload PO document (PDF, image or Excel · up to 5 MB)',h('input',{type:'file',accept:'.pdf,.png,.jpg,.jpeg,.xlsx',disabled:locked,onChange:upload}))),
     !order&&editor&&!stagedFile&&h('div',{className:'ws-po-document-next'},h('span',{className:'ws-po-document-icon','aria-hidden':true},h('svg',{width:22,height:22,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:1.6},h('path',{d:'M14 2H5v20h14V7zM14 2v5h5M8 12h8M8 16h6'}))),h('div',null,h('strong',null,'Attach the original PO next'),h('p',null,'Save this draft to upload a PDF, image or Excel file.'))),
     importRows&&editor&&h('section',{className:'ws-po-section ws-po-import-review'},h('div',{className:'ws-po-section-heading'},h('h4',null,'Review imported items'),h('span',null,importRows.length+' lines')),h('div',{className:'ws-po-review-summary'},h('strong',null,importRows.filter(r=>r.itemId).length+' matched'),h('span',null,importRows.filter(r=>!r.itemId).length+' need a stock item')),h('p',null,'Match each PO line to stock, or create a missing item. Check quantities in the selected stock unit.'),
      importRows.map(row=>{const item=lookup(row.itemId),suggestions=window.matchPurchaseOrderLine(row,data.items).candidates;const matches=data.items.filter(i=>row.search?identity(i).toLowerCase().includes(row.search.toLowerCase()):suggestions.includes(i.id));const options=[...(item?[item]:[]),...matches.filter(i=>i.id!==row.itemId).slice(0,99)];const choosing=!item||row.editMatch;const change=patch=>{setImportReviewed(false);setImportRows(importRows.map(r=>r.key===row.key?{...r,...patch}:r));};return h('article',{key:row.key,className:'ws-po-import-line'+(!item?' needs-match':'')},h('div',{className:'ws-po-import-source'},h('span',{className:'ws-po-source-label'},'PO LINE '+(row.key+1)),h('strong',null,row.sku||'No source stock code'),h('p',null,row.description),h('small',null,[row.colour,row.dimensions,row.lengthMm?row.lengthMm+' mm':''].filter(Boolean).join(' · ')),h('div',{className:'ws-po-source-qty'},h('span',null,'Ordered on PO'),h('strong',null,(row.quantity??'Unclear')+' '+(row.unit||'(unit unclear)')))),h('div',{className:'ws-po-import-match'},h('span',{className:'ws-po-status '+(item?'open':'partial')},item?'Stock item selected':'Needs a stock item'),choosing&&h('label',{className:'ws-field'},'Find stock',h('input',{value:row.search,disabled:locked,placeholder:'Search code, name, colour or size',onChange:e=>change({search:e.target.value})})),choosing&&h('label',{className:'ws-field'},'Stock item',h('select',{value:row.itemId,disabled:locked,onChange:e=>change({itemId:e.target.value})},h('option',{value:''},options.length?'Select the correct stock item':'No matching stock — search or create below'),options.map(i=>h('option',{key:i.id,value:i.id},identity(i))))),item&&h('div',{className:'ws-po-selected-stock'},h('strong',null,item.name),h('span',null,[item.sku,item.colour||item.color,item.dimensions,item.lengthMm?item.lengthMm+' mm':null].filter(Boolean).join(' · '))),item&&!choosing&&button('Change stock item',()=>change({editMatch:true})),isAdmin&&choosing&&h('div',{className:'ws-po-create-link'},h('span',null,'Item not in your stock list?'),button('Create stock item',()=>startStock(row))),h('label',{className:'ws-field'},'Ordered quantity'+(item?' ('+item.unit+')':''),h('input',{type:'number',min:item?.legacy?1:0.001,max:1e9,step:item?.legacy?1:0.001,value:row.ordered,disabled:locked,onChange:e=>change({ordered:e.target.value})})),button('Remove source line',()=>{setImportReviewed(false);setImportRows(importRows.filter(r=>r.key!==row.key));})));}),
      h('label',{className:'ws-po-import-confirm'},h('input',{type:'checkbox',checked:importReviewed,disabled:locked,onChange:e=>setImportReviewed(e.target.checked)}),h('span',null,'I checked the stock matches, colours, sizes, units and quantities against the document.')),
      button('Use reviewed items',useImport,locked||invalidImport,true),button('Enter items manually',()=>{setImportRows(null);setImportReviewed(false);setNotice('Document retained. Add the stock items below.');})),
     editor&&!importRows?h('section',{className:'ws-po-section ws-po-items'},h('div',{className:'ws-po-section-heading'},h('h4',null,'Ordered items'),h('span',{className:'ws-po-item-count'},selectedLines.length+' '+(selectedLines.length===1?'item':'items'))),h('p',null,'Find a stock item, check its colour and size, then add the ordered quantity.'),h('div',{className:'ws-po-add-line'},h('label',{className:'ws-field'},'Search stock',h('input',{value:itemSearch,placeholder:'Name, code, colour or size',disabled:locked,onChange:e=>{setItemSearch(e.target.value);setItemId('');}})),h('label',{className:'ws-field'},'Stock item',h('select',{value:itemId,disabled:locked,onChange:e=>setItemId(e.target.value)},h('option',{value:''},'Choose an item'),candidates.map(i=>h('option',{key:i.id,value:i.id},identity(i))))),h('label',{className:'ws-field ws-po-add-quantity'},'Quantity'+(addingItem?' ('+addingItem.unit+')':''),h('input',{'aria-label':'Quantity to add',type:'number',inputMode:addingItem?.legacy?'numeric':'decimal',min:addingItem?.legacy?1:0.001,max:1e9,step:addingItem?.legacy?1:0.001,placeholder:'Qty',value:itemQuantity,disabled:locked,onChange:e=>setItemQuantity(e.target.value),onKeyDown:e=>{if(e.key==='Enter'){e.preventDefault();addLine();}}})),button('Add item',addLine,locked||!itemId||!validAddingQuantity||selectedLines.length>=200)),isAdmin&&h('div',{className:'ws-po-create-link'},h('span',null,'Cannot find the stock item?'),button('Create stock item',()=>startStock())),
      !selectedLines.length&&h('div',{className:'ws-po-empty-items'},h('strong',null,'No items added yet'),h('p',null,'Find an existing item above, or create a stock item without leaving this PO.')),
      selectedLines.map((l,index)=>{const i=lookup(l.itemId);return h('div',{className:'ws-po-line',key:l.itemId},h('div',null,h('strong',null,i?.name||'Item no longer available'),h('p',null,i?identity(i):l.itemId),(order?.lines.find(row=>row.itemId===l.itemId)?.received||0)>0&&h('small',null,num(order.lines.find(row=>row.itemId===l.itemId).received)+' already received · keep this line')),h('label',{className:'ws-field'},'Ordered ('+(i?.unit||'units')+')',h('input',{type:'number',min:Math.max(order?.lines.find(row=>row.itemId===l.itemId)?.received||0,i?.legacy?1:0.001),step:i?.legacy?1:0.001,value:l.ordered,disabled:locked,'aria-label':'Ordered quantity for '+(i?.sku||i?.name),onChange:e=>setEditor({...editor,lines:editor.lines.map((v,n)=>n===index?{...v,ordered:e.target.value}:v)})})),button('Remove',()=>setEditor({...editor,lines:editor.lines.filter((_,n)=>n!==index)}),locked||(order?.lines.find(row=>row.itemId===l.itemId)?.received||0)>0||(order?.issues||[]).some(i=>i.itemId===l.itemId)));})
     ):order&&h(React.Fragment,null,order.notes&&h('p',null,order.notes),h('h4',null,review?'Review this delivery':'PO items'),['open','partial'].includes(order.status)&&h('p',null,'Enter accepted quantities delivered today. Leave missing items blank or zero. Only these quantities will be added to stock.'),
      (review?receiptLines:order.lines).map(l=>h('div',{className:'ws-po-line ws-po-receive-line',key:l.itemId},h('div',null,h('strong',null,l.name),h('p',null,[l.sku,l.colour,l.dimensions,l.lengthMm?l.lengthMm+' mm':null].filter(Boolean).join(' · ')),h('div',{className:'ws-po-amounts'},h('span',null,'Ordered ',h('b',null,num(l.ordered))),h('span',null,'Received ',h('b',null,num(l.received))),h('span',null,'Outstanding ',h('b',null,num(remaining(l)))))),['open','partial'].includes(order.status)&&remaining(l)>0?(review?h('strong',null,'Receive '+num(delivery.quantities[l.itemId])+' '+l.unit):h('label',{className:'ws-field'},'Arrived ('+l.unit+')',h('input',{type:'number',inputMode:'decimal',min:0,max:remaining(l),step:/^(variant|offcut):/.test(l.itemId)?1:0.001,placeholder:'0',value:delivery.quantities[l.itemId]??'',disabled:locked,'aria-label':'Receive '+l.sku+' '+l.name,onChange:e=>setDelivery({...delivery,quantities:{...delivery.quantities,[l.itemId]:e.target.value}})}))):h('span',null,l.received===l.ordered?'Complete':num(remaining(l))+' not received'))),
      ['open','partial'].includes(order.status)&&h('div',{className:'ws-fields'},h('label',{className:'ws-field'},'Delivery docket / reference',h('input',{value:delivery.reference,disabled:locked||review,maxLength:160,onChange:e=>setDelivery({...delivery,reference:e.target.value})})),h('label',{className:'ws-field'},'Delivery notes',h('input',{value:delivery.notes,disabled:locked||review,maxLength:1000,placeholder:'e.g. Missing box, damaged items not accepted',onChange:e=>setDelivery({...delivery,notes:e.target.value})}))),
      !!order.receipts.length&&h('details',{className:'ws-po-history'},h('summary',null,'Delivery history ('+order.receipts.length+')'),order.receipts.map(r=>h('div',{key:r.id},h('strong',null,new Date(r.at).toLocaleString('en-AU')+' · '+r.user),h('p',null,[r.reference,r.notes].filter(Boolean).join(' · ')),r.lines.map(l=>{const line=order.lines.find(i=>i.itemId===l.itemId);return h('p',{key:l.itemId},num(l.quantity)+' '+(line?.unit||'')+' · '+(line?.name||l.itemId));}))))
     ),
     order&&!editor&&h('section',{className:'ws-po-issues ws-po-section'},
      h('div',{className:'ws-po-section-heading'},h('h4',null,'Delivery issues'),h('span',null,(order.issues||[]).filter(i=>i.status==='open').length+' open')), (order.issues||[]).some(i=>i.status==='open')&&isAdmin&&h('p',{className:'ws-po-warning'},'Resolve open delivery issues before closing this PO short.'),
      h('p',null,'Report rejected, missing or incorrect items here. Reports do not add or remove stock. Receive only accepted items above; record damage separately if stock was already accepted.'),
      ['open','partial','received'].includes(order.status)&&!issueForm&&button('Report delivery issue',()=>{setIssueForm({itemId:order.lines[0]?.itemId||'',kind:'damaged',quantity:'',notes:'',deliveryReference:delivery.reference});setResolution(null);}),
      issueForm&&h('div',{className:'ws-po-issue-form'},
       h('div',{className:'ws-fields'},
        h('label',{className:'ws-field'},'PO item',h('select',{value:issueForm.itemId,disabled:locked,onChange:e=>setIssueForm({...issueForm,itemId:e.target.value})},order.lines.map(l=>h('option',{key:l.itemId,value:l.itemId},identity(l))))),
        h('label',{className:'ws-field'},'Issue type',h('select',{value:issueForm.kind,disabled:locked,onChange:e=>setIssueForm({...issueForm,kind:e.target.value})},Object.entries(issueLabels).map(([value,label])=>h('option',{key:value,value},label)))),
        h('label',{className:'ws-field'},'Affected quantity',h('input',{type:'number',min:0.001,max:order.lines.find(l=>l.itemId===issueForm.itemId)?.ordered,step:/^(variant|offcut):/.test(issueForm.itemId)?1:0.001,value:issueForm.quantity,disabled:locked,onChange:e=>setIssueForm({...issueForm,quantity:e.target.value})})),
        h('label',{className:'ws-field'},'Delivery reference (optional)',h('input',{value:issueForm.deliveryReference,maxLength:160,disabled:locked,onChange:e=>setIssueForm({...issueForm,deliveryReference:e.target.value})}))),
       h('label',{className:'ws-field'},'What happened?',h('textarea',{value:issueForm.notes,maxLength:1000,rows:3,disabled:locked,onChange:e=>setIssueForm({...issueForm,notes:e.target.value})})),
       h('div',{className:'ws-actions'},button('Discard issue',()=>setIssueForm(null)),button('Save delivery issue',()=>mutate({action:'report_issue',...issueForm}),locked||!issueForm.notes.trim()||!issueForm.itemId||!(Number(issueForm.quantity)>0),true))),
      !(order.issues||[]).length&&!issueForm&&h('p',null,'No delivery issues reported.'),
      (order.issues||[]).map(i=>h('article',{key:i.id,className:'ws-po-issue-card'},
       h('div',{className:'ws-po-section-heading'},h('strong',null,issueLabels[i.kind]+' · '+i.name),h('span',{className:'ws-po-status '+(i.status==='open'?'partial':'received')},i.status==='open'?'Needs attention':'Resolved')),
       h('p',null,num(i.quantity)+' '+i.unit+(i.reference?' · '+i.reference:'')),
       h('p',{className:'ws-po-issue-notes'},i.notes),
       h('small',null,'Reported by '+i.user+' · '+new Date(i.at).toLocaleString('en-AU')),
       h('div',{className:'ws-po-issue-photos'},order.attachments.filter(f=>f.issueId===i.id).map(f=>h('div',{key:f.id},button(f.name,()=>download(f)),h('small',null,'Added by '+f.uploadedBy+' · '+new Date(f.uploadedAt).toLocaleString('en-AU'))))),
       i.status==='open'&&h(React.Fragment,null,order.attachments.filter(f=>f.issueId===i.id).length<5&&h('label',{className:'ws-field'},'Add photo (JPG or PNG, up to 5 MB)',h('input',{type:'file',accept:'image/jpeg,image/png',disabled:locked,onChange:e=>upload(e,i.id)})),isAdmin&&button('Resolve issue',()=>{setResolution({issueId:i.id,reason:''});setIssueForm(null);})),
       i.status==='resolved'&&h('div',{className:'ws-notice'},h('strong',null,'Resolved by '+i.resolvedBy+' · '+new Date(i.resolvedAt).toLocaleString('en-AU')),h('p',null,i.resolution)),
       resolution?.issueId===i.id&&h('div',{className:'ws-po-issue-form'},h('label',{className:'ws-field'},'Resolution',h('textarea',{rows:3,maxLength:1000,disabled:locked,value:resolution.reason,placeholder:'e.g. Supplier confirmed replacement on the next delivery',onChange:e=>setResolution({...resolution,reason:e.target.value})})),h('div',{className:'ws-actions'},button('Back',()=>setResolution(null)),button('Confirm resolution',()=>mutate({action:'resolve_issue',...resolution}),locked||!resolution.reason.trim(),true))))
      )),
     order?.status==='closed_short'&&h('div',{className:'ws-po-warning'},h('strong',null,'Closed short by '+order.closedBy+' · '+new Date(order.closedAt).toLocaleString('en-AU')),h('p',null,order.closeReason),h('p',null,'The unreceived balance is closed and excluded from incoming stock.')),
     closeReason!==null&&h('div',{className:'ws-po-warning'},h('label',{className:'ws-field'},'Reason for closing short',h('textarea',{value:closeReason,maxLength:500,rows:3,disabled:locked,onChange:e=>setCloseReason(e.target.value)})),h('p',null,'The remaining quantities will no longer be expected. Ordered quantities, received stock and delivery history will be preserved.'),
      order.lines.filter(l=>remaining(l)>0).map(l=>h('p',{key:l.itemId},num(remaining(l))+' '+l.unit+' · '+l.name+' will not be received')),
      button('Keep PO open',()=>setCloseReason(null)),button('Confirm close short',()=>mutate({action:'close_short',reason:closeReason}),locked||!closeReason.trim(),true)),
     order?.status==='cancelled'&&h('p',null,'Cancelled by '+order.cancelledBy+': '+order.cancelReason),
     cancelReason!==null&&h('div',{className:'ws-po-warning'},h('label',{className:'ws-field'},'Reason for cancelling the remaining order',h('input',{value:cancelReason,disabled:locked,onChange:e=>setCancelReason(e.target.value)})),h('p',null,'Previously received stock and delivery history will be kept.'),button('Keep PO open',()=>setCancelReason(null)),button('Confirm cancellation',()=>mutate({action:'cancel',reason:cancelReason}),locked||!cancelReason.trim()))
    )
   ),
   h('div',{className:'ws-actions ws-count-footer'},editor&&h('div',{className:'ws-po-save-hint'},h('strong',null,order?(order.status==='draft'?'Draft purchase order':'Edit purchase order'):'Create your draft'),h('span',null,!editor.reference.trim()||!editor.supplier.trim()?'Enter a PO number and supplier to save.':dirty?'Unsaved changes':order?(order.status==='draft'?'Save any changes before making this PO available.':'Received items and delivery history are preserved.'):'Stock quantities change only when a delivery is received.')),(selected||editor)?button('Back to POs',()=>{setSelected(null);setEditor(null);setReview(false);setCancelReason(null);setIssueForm(null);setCloseReason(null);setResolution(null);setStagedFile(null);setImportRows(null);setImportWarnings([]);}):button('Refresh',load),!selected&&!editor&&isAdmin&&button('New purchase order',newOrder,locked||!data,true),order&&isAdmin&&!editor&&button('Duplicate PO',duplicateOrder),order&&isAdmin&&!editor&&order.status!=='closed_short'&&button('Edit PO',editOrder),order&&editor&&order.status!=='draft'&&button('Cancel editing',()=>setEditor(null)),editor&&button(order&&order.status!=='draft'?'Save changes':'Save draft',()=>mutate({action:'save',...editor}),locked||!!importRows||!editor.reference.trim()||!editor.supplier.trim(),true),editor&&(!order||order.status==='draft')&&button('Save & make available',()=>mutate({action:'save',...editor,publishAfterSave:true}),locked||!!importRows||!editor.reference.trim()||!editor.supplier.trim()||!editor.lines.length||(!stagedFile&&!order?.attachments.some(f=>!f.issueId)),true),order?.status==='draft'&&isAdmin&&button('Make available for receiving',()=>mutate({action:'publish'}),locked||dirty||!order.attachments.length||!order.lines.length,true),order&&!editor&&['open','partial'].includes(order.status)&&(review?h(React.Fragment,null,button('Edit quantities',()=>setReview(false)),button('Confirm receipt — add to stock',()=>mutate({action:'receive',deliveryReference:delivery.reference,notes:delivery.notes,lines:receiptLines.map(l=>({itemId:l.itemId,quantity:delivery.quantities[l.itemId]}))}),locked||invalidReceipt,true)):button('Review delivery',()=>setReview(true),locked||invalidReceipt,true)),order&&!editor&&isAdmin&&['open','partial'].includes(order.status)&&closeReason===null&&button('Close short',()=>{setCloseReason('');setCancelReason(null);},locked||(order.issues||[]).some(i=>i.status==='open')),order&&(!editor||order.status==='draft')&&isAdmin&&['draft','open','partial'].includes(order.status)&&cancelReason===null&&button('Cancel PO',()=>{setCancelReason('');setCloseReason(null);}))
  )));
 };
};
